table 'Data Validation'
	lineageTag: 1090613e-0721-904f-d79d-696635373bf2

	column Value
		dataType: string
		lineageTag: 9f63f89b-99f9-bb9c-9d0b-30c0f93f0c65
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Label
		dataType: string
		lineageTag: be61d049-2fd2-a62c-b24c-dcd8ff8352f8
		summarizeBy: none
		sourceColumn: Label

		annotation SummarizationSetBy = Automatic

	partition 'Data Validation' = m
		mode: import
		source =
			let
			    Source = Table.FromRows({{"Data Delivery Trend", "Data Delivery Trend"}, {"Error Rate", "Error Rate"}, {"Validation Failure Rate", "Validation Failure Rate"}}, type table [#"Value" = text, #"Label" = text])
			in
			    Source

	annotation PBI_ResultType = Table
