table Sheet1
	lineageTag: 0643205f-e9e1-0f7b-e205-da8eee89a0f7

	column 'Data Freshness'
		dataType: double
		lineageTag: 893b70ec-570d-eafa-6a9f-34dff795604c
		summarizeBy: sum
		sourceColumn: Data_Freshness

		annotation SummarizationSetBy = Automatic

	column 'Data Vendor'
		dataType: string
		lineageTag: 800a1df1-de95-adfe-c9b6-a4f555e7647e
		summarizeBy: none
		sourceColumn: Data_Vendor

		annotation SummarizationSetBy = Automatic

	column Dataset
		dataType: string
		lineageTag: 3e5bfb5a-4091-93a4-acb2-91600121cd55
		summarizeBy: none
		sourceColumn: Dataset

		annotation SummarizationSetBy = Automatic

	column 'Duplication Rate Pct'
		dataType: double
		lineageTag: 7216e160-ab61-6d50-9171-656b63d91cee
		summarizeBy: sum
		sourceColumn: Duplication_Rate_Pct

		annotation SummarizationSetBy = Automatic

	column 'Error Rate Pct'
		dataType: double
		lineageTag: c74770f3-194d-f8af-d43c-a2a0509919af
		summarizeBy: sum
		sourceColumn: Error_Rate_Pct

		annotation SummarizationSetBy = Automatic

	column 'Incident Frequency'
		dataType: double
		lineageTag: d034dfa7-0ad9-5f8e-8695-885ebfc5e750
		summarizeBy: sum
		sourceColumn: Incident_Frequency

		annotation SummarizationSetBy = Automatic

	column 'Mean Time Between Failures Hours'
		dataType: double
		lineageTag: f9ffd29a-00bd-9a85-a3cd-1bb046f4707b
		summarizeBy: sum
		sourceColumn: Mean_Time_Between_Failures_Hours

		annotation SummarizationSetBy = Automatic

	column 'Mean Time to Fix Failure Hours'
		dataType: double
		lineageTag: f5c12849-1162-db13-0141-ede2b76c2d6f
		summarizeBy: sum
		sourceColumn: Mean_Time_to_Fix_Failure_Hours

		annotation SummarizationSetBy = Automatic

	column Module
		dataType: string
		lineageTag: 36f4984c-25f6-aa3b-360a-7a13b87f38fa
		summarizeBy: none
		sourceColumn: Module

		annotation SummarizationSetBy = Automatic

	column 'Null Value Rate Pct'
		dataType: double
		lineageTag: 1db41d95-3694-1a91-47bb-845e917cf69b
		summarizeBy: sum
		sourceColumn: Null_Value_Rate_Pct

		annotation SummarizationSetBy = Automatic

	column 'On Time Data Delivery Rate Pct'
		dataType: double
		lineageTag: 0bc781ca-e5de-ffb1-9248-245643558979
		summarizeBy: sum
		sourceColumn: On_Time_Data_Delivery_Rate_Pct

		annotation SummarizationSetBy = Automatic

	column 'Pipeline Success Rate Pct'
		dataType: double
		lineageTag: 108b0966-15ef-b178-818c-083e27877f19
		summarizeBy: sum
		sourceColumn: Pipeline_Success_Rate_Pct

		annotation SummarizationSetBy = Automatic

	column 'Record Completeness Score Pct'
		dataType: double
		lineageTag: 37b03d56-3912-2228-4e40-1259eaf2ea2b
		summarizeBy: sum
		sourceColumn: Record_Completeness_Score_Pct

		annotation SummarizationSetBy = Automatic

	column 'Record ID'
		dataType: string
		lineageTag: 19530fa3-28e3-57a3-f9a9-170770eacd5d
		summarizeBy: none
		sourceColumn: Record_ID

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: ffe8f397-3f49-0228-3f82-5f39fcf25fbd
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Time Period'
		dataType: string
		lineageTag: 332e0a7f-0acd-c410-f6d6-b72c82e2ff0b
		summarizeBy: none
		sourceColumn: Time_Period

		annotation SummarizationSetBy = Automatic

	column 'User Reported Issues'
		dataType: int64
		lineageTag: 8e58341f-e30e-8d8b-86de-5bca522a6cb5
		summarizeBy: sum
		sourceColumn: User_Reported_Issues

		annotation SummarizationSetBy = Automatic

	column 'Validation Failure Rate Pct'
		dataType: double
		lineageTag: 7ac5a212-de03-f9d7-1fb9-72013284fd21
		summarizeBy: sum
		sourceColumn: Validation_Failure_Rate_Pct

		annotation SummarizationSetBy = Automatic

	column 'Week format'
		dataType: string
		lineageTag: 3975b7b8-2cd5-d79a-c18e-04b77c57870e
		summarizeBy: none
		sourceColumn: Week_format

		annotation SummarizationSetBy = Automatic

	column Completeness
		dataType: double
		lineageTag: 1ce8bac9-d373-8ac7-b9ef-4dfcbd6b5240
		summarizeBy: none
		sourceColumn: Completeness

		annotation SummarizationSetBy = Automatic

	column Uniqueness
		dataType: double
		lineageTag: 9d067c04-a832-1ccb-8620-c58a0b7dee3f
		summarizeBy: none
		sourceColumn: Uniqueness

		annotation SummarizationSetBy = Automatic

	column Validity
		dataType: double
		lineageTag: 3ccd9c74-17ba-a36e-0f6e-292527d3d82c
		summarizeBy: none
		sourceColumn: Validity

		annotation SummarizationSetBy = Automatic

	column Accuracy
		dataType: double
		lineageTag: 356f7d58-a2b6-0c6b-f71f-02673f5cf1d8
		summarizeBy: none
		sourceColumn: Accuracy

		annotation SummarizationSetBy = Automatic

	column Timeliness
		dataType: double
		lineageTag: 04476a14-b368-1651-ddfc-1b260e357f5e
		summarizeBy: none
		sourceColumn: Timeliness

		annotation SummarizationSetBy = Automatic

	column Consistency
		dataType: double
		lineageTag: 720224f0-1d84-e2b3-615b-a2df2a7a627a
		summarizeBy: none
		sourceColumn: Consistency

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		lineageTag: 6f911922-3080-8f9a-7b9c-27972dd508a6
		summarizeBy: none
		sourceColumn: Date
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Trunc of Date' = DATE(YEAR([Date]), 1, 1)
		dataType: dateTime
		lineageTag: 7434c332-548d-8558-0c78-9d0cc693bb5c
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Quarter of Date' = DATE(YEAR([Date]), (QUARTER([Date])-1)*3+1, 1)
		dataType: dateTime
		lineageTag: 9721a58d-ee7c-7b9a-08fc-70ceadbfa247
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Month of Date' = DATE(YEAR([Date]), MONTH([Date]), 1)
		dataType: dateTime
		lineageTag: ac8d4021-a52e-d485-3222-e4a05fa021e2
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Month Number of Date' = MONTH([Date])
		dataType: int64
		lineageTag: aabf97a9-fe48-8fe4-171a-2fc8650838fa
		summarizeBy: none
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Year of Date' = YEAR([Date])
		dataType: int64
		lineageTag: ecf61bb7-3584-74fe-a800-d4318d7492fd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quarter of Date' = "Qtr " & ROUNDUP(MONTH([Date]) / 3, 0)
		dataType: string
		lineageTag: de716d7b-ccef-1c0d-af54-e6c1762ed670
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month of Date' = FORMAT([Date], "MMMM")
		dataType: string
		lineageTag: 45aefc2a-c271-9593-eaa9-fedc832f8264
		summarizeBy: none
		sortByColumn: 'Month Number of Date'

		annotation SummarizationSetBy = Automatic

	column 'Day of Date' = DAY([Date])
		dataType: int64
		lineageTag: 334afb36-906b-fe62-18a5-f66fae8f2085
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	measure 'Data Delivery Trend' = SUM('Sheet1'[On Time Data Delivery Rate Pct])
		lineageTag: 2e34506d-0481-8a70-2275-1099a3c27947

		annotation SummarizationSetBy = Automatic

	measure 'Data Reported Issues' = SUM('Sheet1'[User Reported Issues])
		lineageTag: c71a0252-87ec-2975-fe52-4aec164d771e

		annotation SummarizationSetBy = Automatic

	measure 'Error Rate' = SUM('Sheet1'[Error Rate Pct])
		lineageTag: 40a46a1c-6412-65cc-3a26-b37614ec9a67

		annotation SummarizationSetBy = Automatic

	measure 'Pipeline Success Rate' = SUM('Sheet1'[Pipeline Success Rate Pct]) * 0.1
		lineageTag: a64808e3-6ade-912c-80c7-517427b75d80
		formatString: 0%

		annotation SummarizationSetBy = Automatic

	measure 'Accuracy Parameter' = SUM('Sheet1'[Accuracy])
		lineageTag: 9bad1991-8d15-16ba-0975-f155bb700f33

		annotation SummarizationSetBy = Automatic

	measure 'Completeness Parameter' = SUM('Sheet1'[Completeness])
		lineageTag: adf78852-1834-c395-e106-e97b47f7aab1

		annotation SummarizationSetBy = Automatic

	measure 'Consistency Parameter' = SUM('Sheet1'[Consistency])
		lineageTag: 443e3e3d-d197-0eef-85f3-545b81f7460f

		annotation SummarizationSetBy = Automatic

	measure 'Timeliness Parameter' = SUM('Sheet1'[Timeliness])
		lineageTag: ddf41e68-a502-cec4-11f0-a29d3df67527

		annotation SummarizationSetBy = Automatic

	measure 'Uniqueness Parameter' = SUM('Sheet1'[Uniqueness])
		lineageTag: fe7fb59e-9787-269c-08c8-18459bdf2e45

		annotation SummarizationSetBy = Automatic

	measure 'Validity Parameter' = SUM('Sheet1'[Validity])
		lineageTag: bf06ffbc-27e7-6e27-9093-a600b87d0fa4

		annotation SummarizationSetBy = Automatic

	measure 'Validation Failure Rate' = SUM('Sheet1'[Validation Failure Rate Pct])
		lineageTag: 72a69191-9abb-ab7e-2855-7cff04f4a3bb
		formatString: 0%

		annotation SummarizationSetBy = Automatic

	measure 'Refresh Date' = "31-Dec-2024"
		lineageTag: dd82ca2d-a884-b55b-981e-61415ad77acb

		annotation SummarizationSetBy = Automatic

	measure 'Data Quality CF' = SWITCH(SELECTEDVALUE('Data Quality'[Value]), "Accuracy", 'Sheet1'[Accuracy Parameter], "Consistency", 'Sheet1'[Consistency Parameter], "Completeness", 'Sheet1'[Completeness Parameter], "Timeliness", 'Sheet1'[Timeliness Parameter], "Uniqueness", 'Sheet1'[Uniqueness Parameter], "Validity", 'Sheet1'[Validity Parameter])
		lineageTag: f88bea66-eac5-bcc1-6cf8-faf830698aaa

		annotation SummarizationSetBy = Automatic

	measure 'Data Validation CF' = SWITCH(SELECTEDVALUE('Data Validation'[Value]), "Data Delivery Trend", 'Sheet1'[Data Delivery Trend], "Error Rate", 'Sheet1'[Error Rate], "Validation Failure Rate", 'Sheet1'[Validation Failure Rate])
		lineageTag: e604ff58-cefd-afe4-5b07-a3d6221b0978

		annotation SummarizationSetBy = Automatic

	measure Blank = ""
		lineageTag: 108349f0-d5c0-49d2-3f7c-e75ecf948740

		annotation SummarizationSetBy = Automatic

	measure UserInfo = USERNAME ()
		lineageTag: 646fa200-7ec4-a29a-0a7a-ea181c49203b

		annotation SummarizationSetBy = Automatic

	measure 'Reset Filters' = "Reset"
		lineageTag: b791b51a-c793-f264-9e88-b66834e5322f

		annotation SummarizationSetBy = Automatic

	measure 'avg(0)' = AVERAGE(0)
		lineageTag: 8de6f0f5-a098-a94f-cbad-fa0a7f05c55d

		annotation SummarizationSetBy = Automatic

	measure 'avg(0) (Measure)' = AVERAGE(0)
		lineageTag: a1adf93e-5fe4-d2f1-42e8-aec7b958394c

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: e704c4b3-ea23-2c35-8e1b-d79ac5434409

		level Year
			lineageTag: b3825c4a-6d10-3ce9-379f-9cb624ebc006
			column: 'Year of Date'

		level Quarter
			lineageTag: 95d6b0c0-483e-4741-7f85-e02a4da10b57
			column: 'Quarter of Date'

		level Month
			lineageTag: 6fd5255e-7dc3-7cd1-de1c-1b561e0bb5b4
			column: 'Month of Date'

		level Day
			lineageTag: e6d3c803-5593-f8da-056b-f0ba55aeadfd
			column: 'Day of Date'

	partition Sheet1 = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents("C:\Users\SnehVirenShah\Downloads\TWBX_to_PBIP_FIXED\TWBX_to_PBIP_FIXED\TurboBI Version 0515\uploads\d460267e-3aef-4bb5-9598-b845678268f8\DQM Dashboard_pbip\DQM Dashboard.SemanticModel\data\federated.0kmc5wt0wtr_f839b29e\Extract.Extract.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"Dataset", type text}, {"Module", type text}, {"Completeness", type number}, {"Uniqueness", type number}, {"Validity", type number}, {"Accuracy", type number}, {"Timeliness", type number}, {"Consistency", type number}, {"Status", type text}, {"Week_format", type text}, {"Record_ID", type text}, {"Data_Vendor", type text}, {"Date", type datetime}, {"Time_Period", type text}, {"Pipeline_Success_Rate_Pct", type number}, {"Mean_Time_to_Fix_Failure_Hours", type number}, {"Mean_Time_Between_Failures_Hours", type number}, {"Error_Rate_Pct", type number}, {"Record_Completeness_Score_Pct", type number}, {"On_Time_Data_Delivery_Rate_Pct", type number}, {"Validation_Failure_Rate_Pct", type number}, {"Null_Value_Rate_Pct", type number}, {"Duplication_Rate_Pct", type number}, {"User_Reported_Issues", Int64.Type}, {"Data_Freshness", type number}, {"Incident_Frequency", type number}})
			in
			    ChangedTypes

	annotation PBI_ResultType = Table
