table 'netflix_titles.csv'
	lineageTag: ec2e7367-3106-6e35-f6aa-fddb46375dfa

	column Cast
		dataType: string
		lineageTag: c8645986-4e83-00b8-febd-d60f494a973c
		summarizeBy: none
		sourceColumn: cast
		isHidden

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 1423207f-6932-9a78-c08b-6d8095df89f1
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column 'Date Added'
		dataType: dateTime
		lineageTag: b7558c15-21b0-23a9-6e13-449bf53145c9
		summarizeBy: none
		sourceColumn: date_added
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: b28c1bbd-b62d-050c-ec63-c29df0a6cd6e
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column Director
		dataType: string
		lineageTag: cbd3b0e6-68a2-8748-1b79-bbd59c9ceb76
		summarizeBy: none
		sourceColumn: director
		isHidden

		annotation SummarizationSetBy = Automatic

	column Duration
		dataType: string
		lineageTag: 6b23b61c-ac10-2473-b939-0af3fff34ca9
		summarizeBy: none
		sourceColumn: duration

		annotation SummarizationSetBy = Automatic

	column 'Listed In'
		dataType: string
		lineageTag: 1ef53751-7b55-a907-4d00-3b9aad19795a
		summarizeBy: none
		sourceColumn: listed_in

		annotation SummarizationSetBy = Automatic

	column Rating
		dataType: string
		lineageTag: 51dcbc99-8139-d572-899d-06c0a5c3e486
		summarizeBy: none
		sourceColumn: rating

		annotation SummarizationSetBy = Automatic

	column 'Release Year'
		dataType: int64
		lineageTag: dc39eb4f-8aab-710f-339a-8f1fa774deff
		summarizeBy: none
		sourceColumn: release_year

		annotation SummarizationSetBy = Automatic

	column 'Show Id'
		dataType: int64
		lineageTag: a14fe390-b503-3abd-dc98-b21982352711
		summarizeBy: none
		sourceColumn: show_id

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: f537dd79-b72a-51f5-8aff-c2e692f059ef
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 441c91f6-d302-d33b-180e-713e6ba5b3b3
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column 'Month Number of Date Added' = MONTH([Date Added])
		dataType: int64
		lineageTag: 070a5a37-dbc8-6355-bbc1-de85117d606c
		summarizeBy: none
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Year of Date Added' = YEAR([Date Added])
		dataType: int64
		lineageTag: 772d646b-c2d1-13fc-d25a-6039c2bdc416
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quarter of Date Added' = "Qtr " & ROUNDUP(MONTH([Date Added]) / 3, 0)
		dataType: string
		lineageTag: afa2faf9-825f-59a9-79e2-6db4e9c11f9d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month of Date Added' = FORMAT([Date Added], "MMMM")
		dataType: string
		lineageTag: e96686c2-7879-9ef5-7e2f-a9986f547af3
		summarizeBy: none
		sortByColumn: 'Month Number of Date Added'

		annotation SummarizationSetBy = Automatic

	column 'Day of Date Added' = DAY([Date Added])
		dataType: int64
		lineageTag: 8ee79787-ac00-1df8-8658-859cb8f22568
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Added Hierarchy'
		lineageTag: 93156ac6-b882-b364-764d-7a3293d28350

		level Year
			lineageTag: e5e2e887-a5e6-d957-b04c-835347315076
			column: 'Year of Date Added'

		level Quarter
			lineageTag: b5cf06ae-4f3c-5a3c-36cf-fa9593c77847
			column: 'Quarter of Date Added'

		level Month
			lineageTag: e41ff7fd-ded8-d68f-ed10-926eaa006607
			column: 'Month of Date Added'

		level Day
			lineageTag: c5c59b42-cd29-9bb1-5e22-eb79db58939d
			column: 'Day of Date Added'

	partition 'netflix_titles.csv' = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents("C:\Users\SnehVirenShah\Downloads\TWBX_to_PBIP_FIXED\TWBX_to_PBIP_FIXED\Netflix Movies and TV Shows Dashboard_pbip\Netflix Movies and TV Shows Dashboard.SemanticModel\data\federated.1hi58320xulgdr1clpuut0mqw1p2\Extract.Extract.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"show_id", Int64.Type}, {"type", type text}, {"title", type text}, {"director", type text}, {"cast", type text}, {"country", type text}, {"date_added", type datetime}, {"release_year", Int64.Type}, {"rating", type text}, {"duration", type text}, {"listed_in", type text}, {"description", type text}})
			in
			    ChangedTypes

	annotation PBI_ResultType = Table
