table dashboard_data_available_date
	lineageTag: 62de8fc5-c5e4-0ab3-7ff0-a9dce0d98812

	column 'Dashboard Name'
		dataType: string
		lineageTag: 9aa59767-31cd-b2c8-2fb6-5a2371203e72
		summarizeBy: none
		sourceColumn: dashboard_name

		annotation SummarizationSetBy = Automatic

	column 'Date Available Till'
		dataType: string
		lineageTag: 556e5035-bac3-444d-32e4-85722a521b71
		summarizeBy: none
		sourceColumn: date_available_till

		annotation SummarizationSetBy = Automatic

	column 'Last Refresh Date'
		dataType: string
		lineageTag: 30abd061-a247-7da7-ab64-2570ace082b1
		summarizeBy: none
		sourceColumn: last_refresh_date

		annotation SummarizationSetBy = Automatic

	column 'screen Name'
		dataType: string
		lineageTag: 3abf5367-c31a-cc5b-d8f7-993137902e4b
		summarizeBy: none
		sourceColumn: screen_Name

		annotation SummarizationSetBy = Automatic

	measure claims_date = SWITCH(TRUE(), MIN('dashboard_data_available_date'[screen Name]) = "KOMODO CLAIMS", MIN('dashboard_data_available_date'[Date Available Till]))
		lineageTag: de14e79c-06da-ecee-e228-2c498e97e349

		annotation SummarizationSetBy = Automatic

	measure veeva_crm_date = SWITCH(TRUE(), MIN('dashboard_data_available_date'[screen Name]) = "VEEVA CRM", MIN('dashboard_data_available_date'[Date Available Till]))
		lineageTag: 8546a0f2-207d-4702-6836-b9d319751b98

		annotation SummarizationSetBy = Automatic

	measure sp_dispense_date = SWITCH(TRUE(), MIN('dashboard_data_available_date'[screen Name]) = "SP DISPENSE", MIN('dashboard_data_available_date'[Date Available Till]))
		lineageTag: 0c298d9a-dea6-1cd6-8d9c-cffa0dc9f876

		annotation SummarizationSetBy = Automatic

	measure hub_date = SWITCH(TRUE(), MIN('dashboard_data_available_date'[Dashboard Name]) = "HUB", MIN('dashboard_data_available_date'[Date Available Till]))
		lineageTag: 0ba9a6bb-283d-8438-48f5-c6a187add87c

		annotation SummarizationSetBy = Automatic

	measure sd_shipment_date = SWITCH(TRUE(), MIN('dashboard_data_available_date'[screen Name]) = "SD SHIPMENT", MIN('dashboard_data_available_date'[Date Available Till]))
		lineageTag: 10d2bc56-64e8-2a05-5489-66193389e274

		annotation SummarizationSetBy = Automatic

	partition dashboard_data_available_date = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents("C:\Users\SnehVirenShah\Downloads\TWBX_to_PBIP_FIXED\TWBX_to_PBIP_FIXED\TurboBI Version 0514\uploads\f9971b2b-35ca-4b01-a712-b1e4db6cdee2\Account Leads Dashboard_pbip\Account Leads Dashboard (4) (1).SemanticModel\data\federated.1ntliko1rc0_b514a1b0\Extract.Extract.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"dashboard_name", type text}, {"screen_Name", type text}, {"date_available_till", type text}, {"last_refresh_date", type text}})
			in
			    ChangedTypes

	annotation PBI_ResultType = Table
