table tableau_long_view_pt360
	lineageTag: 18b2395d-ed26-8e8a-dfb8-ba84c548fb79

	column 'All Visit Count 5Yr'
		dataType: string
		lineageTag: 4e18f502-7eaf-c83b-8aee-e9dfd6e6d160
		summarizeBy: none
		sourceColumn: all_visit_count_5yr

		annotation SummarizationSetBy = Automatic

	column 'Hco Name'
		dataType: string
		lineageTag: 6ea5b8f5-36a2-69b4-5ddb-20c4a67ccd89
		summarizeBy: none
		sourceColumn: hco_name

		annotation SummarizationSetBy = Automatic

	column 'Hcp Name'
		dataType: string
		lineageTag: d0832abd-3bd2-8458-fa66-72f67dbd2e46
		summarizeBy: none
		sourceColumn: hcp_name

		annotation SummarizationSetBy = Automatic

	column 'Hcp Specialty'
		dataType: string
		lineageTag: c58529fd-0323-8fb9-d113-b8860556cb26
		summarizeBy: none
		sourceColumn: hcp_specialty

		annotation SummarizationSetBy = Automatic

	column Lastvisit
		dataType: string
		lineageTag: 6675425b-8026-2748-77a6-6fa439688c21
		summarizeBy: none
		sourceColumn: lastvisit

		annotation SummarizationSetBy = Automatic

	column 'Patient Id1'
		dataType: string
		lineageTag: 6ee5ed32-dfed-c20e-04cc-cf02a23f7500
		summarizeBy: none
		sourceColumn: patient_id

		annotation SummarizationSetBy = Automatic

	column 'Primary HCO Name'
		dataType: string
		lineageTag: f3ac8acf-a6b2-ac38-e2c1-d7d99844e7a8
		summarizeBy: none
		sourceColumn: primary_hcp_hco_name_2yr

		annotation SummarizationSetBy = Automatic

	column 'Primary Hcp Name 2Yr'
		dataType: string
		lineageTag: 33f406da-3a8e-6dbd-d4fc-6ac8982d4daa
		summarizeBy: none
		sourceColumn: primary_hcp_name_2yr

		annotation SummarizationSetBy = Automatic

	column 'Primary Hcp Npi1'
		dataType: string
		lineageTag: e491edd6-d88e-526d-7475-55febb4986b6
		summarizeBy: none
		sourceColumn: primary_hcp_npi

		annotation SummarizationSetBy = Automatic

	column Recordtype
		dataType: string
		lineageTag: 93bbeaed-c7b5-a3ef-a416-dd016f20a0cf
		summarizeBy: none
		sourceColumn: recordtype

		annotation SummarizationSetBy = Automatic

	column 'Region Id'
		dataType: string
		lineageTag: 01cee747-b11e-5a15-d9b9-1c265aa7874c
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column 'Region Name'
		dataType: string
		lineageTag: f7e0766b-b9ac-9d40-9fc1-9e76dd37d07a
		summarizeBy: none
		sourceColumn: region_name

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: 208db65c-ddae-437d-f755-5ab3bb8d0ba6
		summarizeBy: none
		sourceColumn: territory

		annotation SummarizationSetBy = Automatic

	column 'Territory Id'
		dataType: string
		lineageTag: bbdd5d25-c2db-bedb-6b5f-65f0cea3a24d
		summarizeBy: none
		sourceColumn: territory_id

		annotation SummarizationSetBy = Automatic

	column 'Treatment Type'
		dataType: string
		lineageTag: 2ec1762f-91b6-6dec-e856-ab7f8a82313a
		summarizeBy: none
		sourceColumn: treatment_type

		annotation SummarizationSetBy = Automatic

	partition tableau_long_view_pt360 = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents("C:\Users\SnehVirenShah\Downloads\TWBX_to_PBIP_FIXED\TWBX_to_PBIP_FIXED\TurboBI Version 0514\uploads\f9971b2b-35ca-4b01-a712-b1e4db6cdee2\Account Leads Dashboard_pbip\Account Leads Dashboard (4) (1).SemanticModel\data\federated.1krsj8l110x_c1acecc0\Extract.tableau!long!view!pt360_b969a9eb.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"patient_id", type text}, {"territory", type text}, {"region_name", type text}, {"region_id", type text}, {"territory_id", type text}, {"primary_hcp_hco_name_2yr", type text}, {"primary_hcp_npi", type text}, {"primary_hcp_name_2yr", type text}, {"hco_name", type text}, {"hcp_name", type text}, {"hcp_specialty", type text}, {"all_visit_count_5yr", type text}, {"recordtype", type text}, {"treatment_type", type text}, {"lastvisit", type text}})
			in
			    ChangedTypes

	annotation PBI_ResultType = Table
