table Toggle_view
	lineageTag: 02f50319-745f-67d9-a49b-bb7f3b74e574

	column Value
		dataType: string
		lineageTag: 039d728f-b4e7-e0f2-35b2-9c4e151b5a0c
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Label
		dataType: string
		lineageTag: 6019a450-ad36-acdc-b42b-df6588f48ecb
		summarizeBy: none
		sourceColumn: Label

		annotation SummarizationSetBy = Automatic

	partition Toggle_view = m
		mode: import
		source =
			let
			    Source = Table.FromRows({{"Elaprase", "Elaprase"}, {"Tivi", "Tivi"}}, type table [#"Value" = text, #"Label" = text])
			in
			    Source

	annotation PBI_ResultType = Table
