table FINAL_PLC_JIRA_DATA
	lineageTag: e601a63f-a7dc-0252-7955-0d475f45a514

	column Assignee
		dataType: string
		lineageTag: efceb1d8-3473-2985-a612-9024d8a9e6ff
		summarizeBy: none
		sourceColumn: ASSIGNEE

		annotation SummarizationSetBy = Automatic

	column 'Assignee Id'
		dataType: string
		lineageTag: e7f68c96-5e9e-247c-edc0-00b5a85d3e37
		summarizeBy: none
		sourceColumn: ASSIGNEE_ID
		isHidden

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 4813e9ea-5880-4d61-6cd2-e2189f5672f1
		summarizeBy: none
		sourceColumn: CATEGORY

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		lineageTag: 471b5eb9-a8f8-a61a-e663-06ce67f035bb
		summarizeBy: none
		sourceColumn: CREATED
		isHidden
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Created Date'
		dataType: dateTime
		lineageTag: f4aaadda-2330-d655-04fc-a880910cff78
		summarizeBy: none
		sourceColumn: CREATED_DATE
		isHidden
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column Creator
		dataType: string
		lineageTag: cbb59c14-f168-e2f1-d0c7-602cbde04c69
		summarizeBy: none
		sourceColumn: CREATOR
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Creator Id'
		dataType: string
		lineageTag: 7e01bab4-2e73-962e-0ea1-a33558d4ea0c
		summarizeBy: none
		sourceColumn: CREATOR_ID
		isHidden

		annotation SummarizationSetBy = Automatic

	column Environment
		dataType: string
		lineageTag: 62057715-3911-d629-768d-af860f2ca607
		summarizeBy: none
		sourceColumn: ENVIRONMENT

		annotation SummarizationSetBy = Automatic

	column Epic
		dataType: string
		lineageTag: ee10e077-4bd0-78da-1b81-90f86490de27
		summarizeBy: none
		sourceColumn: EPIC

		annotation SummarizationSetBy = Automatic

	column 'Issue Id'
		dataType: string
		lineageTag: 2e2fbfd9-06d4-ecab-6ffb-66e310897611
		summarizeBy: none
		sourceColumn: ISSUE_ID
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Issue Key'
		dataType: string
		lineageTag: b354f123-18b5-167a-156d-3e90bbda757d
		summarizeBy: none
		sourceColumn: ISSUE_KEY

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: b921f4b3-966e-0432-214b-429a660c3230
		summarizeBy: none
		sourceColumn: ISSUE_TYPE
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Parent Key'
		dataType: string
		lineageTag: 08306107-6ff6-9895-6063-9e8fe9450e66
		summarizeBy: none
		sourceColumn: PARENT_KEY
		isHidden

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 0c2b1d06-b112-3788-f7be-49a42a22c46d
		summarizeBy: none
		sourceColumn: PRIORITY

		annotation SummarizationSetBy = Automatic

	column 'Prod Ops Outcome'
		dataType: string
		lineageTag: 24c30cb5-5d7c-242f-53e7-937abdd0d13c
		summarizeBy: none
		sourceColumn: PROD_OPS_OUTCOME
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Project Description'
		dataType: string
		lineageTag: 02bead1d-2ba5-2920-45e7-bbc2149f0c5e
		summarizeBy: none
		sourceColumn: PROJECT_DESCRIPTION
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Project Key'
		dataType: string
		lineageTag: 3da79116-0ad3-d3ca-3e4c-85241708ba53
		summarizeBy: none
		sourceColumn: PROJECT_KEY
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Project Lead'
		dataType: string
		lineageTag: 04223bc7-4061-2c7b-5671-61a72c5f2aed
		summarizeBy: none
		sourceColumn: PROJECT_LEAD
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Project Lead Id'
		dataType: string
		lineageTag: 5e3340e0-e5a5-a68a-034a-2831fd826a86
		summarizeBy: none
		sourceColumn: PROJECT_LEAD_ID
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Project Name'
		dataType: string
		lineageTag: d3a0cdfb-ee4f-d1ef-0893-bb1572d3d0d3
		summarizeBy: none
		sourceColumn: PROJECT_NAME
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Project Type'
		dataType: string
		lineageTag: 495f1fa6-516c-10e8-26c6-a25366b78d52
		summarizeBy: none
		sourceColumn: PROJECT_TYPE
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Project Url'
		dataType: string
		lineageTag: d9c17aa4-0064-a6c5-5ccd-dfc7919e6cbc
		summarizeBy: none
		sourceColumn: PROJECT_URL
		isHidden

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 039712ed-6dba-3255-5a1d-0dc124cce42f
		summarizeBy: none
		sourceColumn: REGION

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 277b5f3d-bf28-cd40-c225-78ed8b6c3aef
		summarizeBy: none
		sourceColumn: REPORTER
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Reporter Id'
		dataType: string
		lineageTag: 136f24a5-5d66-e4a0-d9e2-d10387f2db87
		summarizeBy: none
		sourceColumn: REPORTER_ID
		isHidden

		annotation SummarizationSetBy = Automatic

	column Resolution
		dataType: string
		lineageTag: 0d0d86ba-ffe6-36a3-d1e0-20fc5424a8cb
		summarizeBy: none
		sourceColumn: RESOLUTION
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Rollover Flag'
		dataType: string
		lineageTag: f4e9a043-8544-fd6f-39d4-1f2a9596ab6b
		summarizeBy: none
		sourceColumn: ROLLOVER_FLAG

		annotation SummarizationSetBy = Automatic

	column 'Region (group)' = SWITCH(TRUE(), [Region] IN { "Canada", "Developed Markets", "EMEA" }, "DE & DM", [Region] )
		dataType: string
		lineageTag: 244394a2-e530-4d14-25c0-74153901ab2b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Sprint
		dataType: string
		lineageTag: 72bf76c3-72e2-f212-3da9-8a5120106b4d
		summarizeBy: none
		sourceColumn: SPRINT

		annotation SummarizationSetBy = Automatic

	column 'Sprint End Date'
		dataType: dateTime
		lineageTag: 0941e23a-b7bf-37d9-e790-747cbd2eaac1
		summarizeBy: none
		sourceColumn: SPRINT_END_DATE
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Sprint Start Date'
		dataType: dateTime
		lineageTag: d9c9028f-6351-5c64-ca95-3335dac2df21
		summarizeBy: none
		sourceColumn: SPRINT_START_DATE
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: b8b12834-5eee-9f5d-7353-a23305bd39c7
		summarizeBy: none
		sourceColumn: STATUS

		annotation SummarizationSetBy = Automatic

	column 'Status Category'
		dataType: string
		lineageTag: 7856e2dc-59a9-ef14-735f-bc8d93b6ddbc
		summarizeBy: none
		sourceColumn: STATUS_CATEGORY
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Status Category Changed'
		dataType: dateTime
		lineageTag: 951850c3-6d40-9c1c-426b-d8a129b2a245
		summarizeBy: none
		sourceColumn: STATUS_CATEGORY_CHANGED
		isHidden
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Story Points'
		dataType: int64
		lineageTag: cc58effd-3c37-2343-3ad2-fd2db5375c35
		summarizeBy: sum
		sourceColumn: STORY_POINTS

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 89bd943c-48e3-128b-d7be-1b7e3043fe8d
		summarizeBy: none
		sourceColumn: SUMMARY

		annotation SummarizationSetBy = Automatic

	column Team
		dataType: string
		lineageTag: 43b487b9-d3e8-00a8-1670-36330a13bbdd
		summarizeBy: none
		sourceColumn: TEAM

		annotation SummarizationSetBy = Automatic

	column Updated
		dataType: dateTime
		lineageTag: e2dfb208-e220-c9b5-b29e-734e06416508
		summarizeBy: none
		sourceColumn: UPDATED
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Sprint Filter Calc' = SWITCH(TRUE(), SELECTEDVALUE('Time'[Value]) = "Current Sprint", 'FINAL_PLC_JIRA_DATA'[Sprint Number] = 'FINAL_PLC_JIRA_DATA'[Max Sprint Number], SELECTEDVALUE('Time'[Value]) = "Previous Sprint", 'FINAL_PLC_JIRA_DATA'[Sprint Number] = 'FINAL_PLC_JIRA_DATA'[Max Sprint Number] - 1, SELECTEDVALUE('Time'[Value]) = "Last 6 Sprints", 'FINAL_PLC_JIRA_DATA'[Sprint Number] >= 'FINAL_PLC_JIRA_DATA'[Max Sprint Number] - 5, SELECTEDVALUE('Time'[Value]) = "Last 12 Sprints", 'FINAL_PLC_JIRA_DATA'[Sprint Number] >= 'FINAL_PLC_JIRA_DATA'[Max Sprint Number] - 11, SELECTEDVALUE('Time'[Value]) = "Last 20 Sprints", 'FINAL_PLC_JIRA_DATA'[Sprint Number] >= 'FINAL_PLC_JIRA_DATA'[Max Sprint Number] - 19, SELECTEDVALUE('Time'[Value]) = "Current YTD", YEAR ('FINAL_PLC_JIRA_DATA'[Sprint End Date]) = YEAR (TODAY() ()), SELECTEDVALUE('Time'[Value]) = "Last Year", YEAR ('FINAL_PLC_JIRA_DATA'[Sprint End Date]) = YEAR (TODAY() ()) - 1, SELECTEDVALUE('Time'[Value]) = "Next 2 Sprints", 'FINAL_PLC_JIRA_DATA'[Sprint Number] > 'FINAL_PLC_JIRA_DATA'[Max Sprint Number] && 'FINAL_PLC_JIRA_DATA'[Sprint Number] <= 'FINAL_PLC_JIRA_DATA'[Max Sprint Number] + 2)
		dataType: boolean
		lineageTag: 2082eab1-3d11-6a65-0bf3-30cdbf5b8dfc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Ticket Type Calc' = SWITCH(TRUE(), SELECTEDVALUE('Ticket Type'[Value]) = "Total", TRUE(), SELECTEDVALUE('Ticket Type'[Value]) = "Rollover", 'FINAL_PLC_JIRA_DATA'[Rollover Flag] = "YES", SELECTEDVALUE('Ticket Type'[Value]) = "Unassigned", ISBLANK ('FINAL_PLC_JIRA_DATA'[Assignee]) || 'FINAL_PLC_JIRA_DATA'[Assignee] = "Not Assigned" || TRIM('FINAL_PLC_JIRA_DATA'[Assignee]) = "", SELECTEDVALUE('Ticket Type'[Value]) = "Assigned", NOT (ISBLANK ('FINAL_PLC_JIRA_DATA'[Assignee]) || 'FINAL_PLC_JIRA_DATA'[Assignee] = "Not Assigned" || TRIM('FINAL_PLC_JIRA_DATA'[Assignee]) = ""))
		dataType: boolean
		lineageTag: 93cc4bea-35d9-0fc2-17d5-8e00a14d2de1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'DZV Summary ASC' = SELECTEDVALUE('Sort By :'[Value]) = "Summary" && SELECTEDVALUE('Order By :'[Value]) = "Ascending"
		dataType: boolean
		lineageTag: 3c3e9b24-b11c-176e-125c-839c74fc80dd
		summarizeBy: none
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'DVZ View by Team' = SELECTEDVALUE('View By'[Value]) = "Team"
		dataType: boolean
		lineageTag: 1d94460b-0c50-7fe3-b47f-a24a3e70c8f5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'DVZ View by Region' = SELECTEDVALUE('View By'[Value]) = "Region"
		dataType: boolean
		lineageTag: 78f3b433-f5c0-2b05-d272-04cffab3b5ab
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'DZV Status DESC' = SELECTEDVALUE('Sort By :'[Value]) = "Status" && SELECTEDVALUE('Order By :'[Value]) = "Descending"
		dataType: boolean
		lineageTag: 48d2048b-07a6-f44f-a1a1-6947313c53fd
		summarizeBy: none
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'DZV Summary DESC' = SELECTEDVALUE('Sort By :'[Value]) = "Summary" && SELECTEDVALUE('Order By :'[Value]) = "Descending"
		dataType: boolean
		lineageTag: db53e2cf-60d6-86a7-6595-0367cfe04047
		summarizeBy: none
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'DZV Status ASC' = SELECTEDVALUE('Sort By :'[Value]) = "Status" && SELECTEDVALUE('Order By :'[Value]) = "Ascending"
		dataType: boolean
		lineageTag: b1766631-45ac-379b-39fc-58d139a4b9b4
		summarizeBy: none
		isHidden

		annotation SummarizationSetBy = Automatic

	measure 'US Story Points' = SWITCH(TRUE(), MIN('FINAL_PLC_JIRA_DATA'[Region (group)]) = "US", MIN('FINAL_PLC_JIRA_DATA'[Story Points]), 0)
		lineageTag: 1df11d60-3281-5556-1fa2-b6a97d462dd7

		annotation SummarizationSetBy = Automatic

	measure 'EMEA Story Points' = SWITCH(TRUE(), MIN('FINAL_PLC_JIRA_DATA'[Region (group)]) = "DE & DM", MIN('FINAL_PLC_JIRA_DATA'[Story Points]), 0)
		lineageTag: 2026a0f4-0946-7ea1-51bd-a75747e08892

		annotation SummarizationSetBy = Automatic

	measure 'JP Story Points' = SWITCH(TRUE(), MIN('FINAL_PLC_JIRA_DATA'[Region (group)]) = "JP", MIN('FINAL_PLC_JIRA_DATA'[Story Points]), 0)
		lineageTag: e003cf24-873c-a624-e536-48fd8a6c12c9

		annotation SummarizationSetBy = Automatic

	measure 'Rollover Count' = SWITCH(TRUE(), MIN('FINAL_PLC_JIRA_DATA'[Rollover Flag]) = "YES", MIN('FINAL_PLC_JIRA_DATA'[Issue Key]))
		lineageTag: b66c426a-6c66-e8d4-7ed7-93541c9a5196

		annotation SummarizationSetBy = Automatic

	measure 'Selected Sprints' = CALCULATE(DISTINCTCOUNT('FINAL_PLC_JIRA_DATA'[Sprint]), ALL('FINAL_PLC_JIRA_DATA'))
		lineageTag: e78f70a8-255f-b821-5146-98a7f47efc41
		isHidden

		annotation SummarizationSetBy = Automatic

	measure 'Avg Selected' = SUM('FINAL_PLC_JIRA_DATA'[Story Points]) / 'FINAL_PLC_JIRA_DATA'[Selected Sprints]
		lineageTag: 5c3c2c7a-9c1f-97a7-e265-4cc80fee1f17
		isHidden

		annotation SummarizationSetBy = Automatic

	measure 'Total Fixed Story Points' = CALCULATE(SUM('FINAL_PLC_JIRA_DATA'[Story Points]), ALL('FINAL_PLC_JIRA_DATA'))
		lineageTag: ab0414a0-4b0d-1761-6eed-becc28241f12

		annotation SummarizationSetBy = Automatic

	measure 'Story Points Header' = "Story Points"
		lineageTag: 415507a3-aa13-a1e8-2a28-c67ebfc20401

		annotation SummarizationSetBy = Automatic

	measure 'Unassigned Tickets' = SWITCH(TRUE(), ISBLANK (MIN('FINAL_PLC_JIRA_DATA'[Assignee])) || MIN('FINAL_PLC_JIRA_DATA'[Assignee]) = "Not Assigned", 1, 0)
		lineageTag: c2b89c55-18b4-b0a2-31e1-22086ff72260

		annotation SummarizationSetBy = Automatic

	measure 'Ticket Logs Upper Line' = "Issue Key : " & MIN('FINAL_PLC_JIRA_DATA'[Issue Key]) & " " & " | Priority : " & MIN('FINAL_PLC_JIRA_DATA'[Priority]) & " " & " | Story Points: " & FORMAT(MIN('FINAL_PLC_JIRA_DATA'[Story Points]), "") & " " & " | Status: " & MIN('FINAL_PLC_JIRA_DATA'[Status]) + CHAR (10)
		lineageTag: 17d0f168-f89e-5989-f913-59f935772126
		isHidden

		annotation SummarizationSetBy = Automatic

	measure 'Ticket Logs Summary' = "Summary : " & MIN('FINAL_PLC_JIRA_DATA'[Summary]) + CHAR (10)
		lineageTag: a82c920e-9e1f-9e01-13d8-70d8ae83a05d
		isHidden

		annotation SummarizationSetBy = Automatic

	measure 'Ticket Logs Bottom Line' = "Developer: " & MIN('FINAL_PLC_JIRA_DATA'[Assignee]) & " " & " | Environment: " & MIN('FINAL_PLC_JIRA_DATA'[Environment]) & " " & " | Category: " & MIN('FINAL_PLC_JIRA_DATA'[Category])
		lineageTag: 7bd7be07-c909-30dd-dd8a-fd7bcee0219f
		isHidden

		annotation SummarizationSetBy = Automatic

	measure 'Sprint Velocity View by Chart' = SELECTEDVALUE('View By'[Value])
		lineageTag: ede279b0-b0c7-c44e-d258-dec9482fb924

		annotation SummarizationSetBy = Automatic

	measure 'Sprint Number' = BLANK() /* TODO: translate Tableau formula -- INT(REGEXP_EXTRACT([SPRINT], '(\d+)')) */
		lineageTag: 3aaeeaa2-edbe-0d54-2ab6-0b1737ba8472

		annotation SummarizationSetBy = Automatic

	measure 'Max Sprint Number' = CALCULATE('FINAL_PLC_JIRA_DATA'[Sprint Number], ALL('FINAL_PLC_JIRA_DATA'))
		lineageTag: b19f98e8-00cc-c235-6d70-7c47bf72eeae

		annotation SummarizationSetBy = Automatic

	measure 'Max Date' = CALCULATE(MAX('FINAL_PLC_JIRA_DATA'[Updated]), ALL('FINAL_PLC_JIRA_DATA'))
		lineageTag: 0a825a8b-3a53-ec1b-bd08-3dfcf44b616f
		formatString: *mmmm d, yyyy

		annotation SummarizationSetBy = Automatic

	measure Blank = ""
		lineageTag: fa36971f-2f50-8871-a3b3-a693cdab2ec2

		annotation SummarizationSetBy = Automatic

	measure 'Sort Calc' = BLANK() /* TODO: translate Tableau formula -- IF [Parameters].[Parameter 8] = 'Summary' THEN (CASE [Parameters].[Parameter 9] WHEN 'Ascending' THEN RANK_UNIQUE(MIN([SUMMARY]),'asc') WHEN 'Descending' THEN RANK_UNIQUE(min([SUMMARY]),'desc') END) ELSEIF [Parameters].[Parameter 8] = 'Status' THEN (CASE [Parameters].[Parameter 9] WHEN 'Ascending' THEN RANK_UNIQUE(min([STATUS]),'asc') WHEN 'Descending' THEN RANK_UNIQUE(min([STATUS]),'desc') END) ELSEIF [Parameters].[Parameter 8] = 'Issue Key' THEN (CASE [Parameters].[Parameter 9] WHEN 'Ascending' THEN RANK_UNIQUE(min([ISSUE_KEY]),'asc') WHEN 'Descending' THEN RANK_UNIQUE(min([ISSUE_KEY]),'desc') END) ELSEIF [Parameters].[Parameter 8] = 'Epic' THEN (CASE [Parameters].[Parameter 9] WHEN 'Ascending' THEN RANK_UNIQUE(min([EPIC]),'asc') WHEN 'Descending' THEN RANK_UNIQUE(min([EPIC]),'desc') END) END */
		lineageTag: c528df80-8798-88f9-502f-c5d65daeb2ec

		annotation SummarizationSetBy = Automatic

	measure 'Total Tickets' = DISTINCTCOUNT('FINAL_PLC_JIRA_DATA'[Issue Key])
		lineageTag: cfb18c24-57cb-bc14-ce83-559b0dbb443b
		isHidden

		annotation SummarizationSetBy = Automatic

	measure 'Assigned Tickets' = DISTINCTCOUNT('FINAL_PLC_JIRA_DATA'[Issue Key]) - 'FINAL_PLC_JIRA_DATA'[Unassigned Tickets]
		lineageTag: 176e129c-90fb-7372-14c5-3c252ede2870

		annotation SummarizationSetBy = Automatic

	measure 'Sprint & Ticket Count' = SELECTEDVALUE('FINAL_PLC_JIRA_DATA'[Sprint]) & " (" & FORMAT(DISTINCTCOUNT('FINAL_PLC_JIRA_DATA'[Issue Key]), "") & ")"
		lineageTag: 41e04237-187f-cfa5-541a-b56606ded447

		annotation SummarizationSetBy = Automatic

	measure 'Reset Parameter' = "Reset Parameter"
		lineageTag: 8b9267c3-2aab-4bc5-1b3c-c0a44fd7ce05

		annotation SummarizationSetBy = Automatic

	measure 'Paraemeter Reset' = "Last 6 Sprints"
		lineageTag: d63fff3c-32ff-b7d1-ae29-b5dfb6307e36

		annotation SummarizationSetBy = Automatic

	measure 'Category & Ticket Count' = SELECTEDVALUE('FINAL_PLC_JIRA_DATA'[Category]) & " (" & FORMAT(DISTINCTCOUNT('FINAL_PLC_JIRA_DATA'[Issue Key]), "") & ")"
		lineageTag: 0104989a-eb64-b9d1-c95d-97329a09b620

		annotation SummarizationSetBy = Automatic

	measure 'Current Sprint Start Date' = CALCULATE(MAX(SWITCH(TRUE(), MIN('FINAL_PLC_JIRA_DATA'[Sprint Start Date]) <= TODAY() (), MIN('FINAL_PLC_JIRA_DATA'[Sprint Start Date]))), ALL('FINAL_PLC_JIRA_DATA'))
		lineageTag: 5346c3bd-b4f6-807f-0d37-7ef73d996a6c

		annotation SummarizationSetBy = Automatic

	measure 'Story Point Calc' = SWITCH(TRUE(), SELECTEDVALUE('Story Points'[Value]) = "Story Points = 0", SUM('FINAL_PLC_JIRA_DATA'[Story Points]) = 0, SELECTEDVALUE('Story Points'[Value]) = "Story Points <> 0", SUM('FINAL_PLC_JIRA_DATA'[Story Points]) > 0, TRUE())
		lineageTag: 27fad844-073a-5b38-9ab9-abfaba9d3a9a

		annotation SummarizationSetBy = Automatic

	measure 'Zero/NonZero' = SWITCH(TRUE(), MIN('FINAL_PLC_JIRA_DATA'[Story Points]) = 0, "Story Points = 0", "Story Points <> 0")
		lineageTag: fa1f3966-019f-998e-67bf-a88ea7715662

		annotation SummarizationSetBy = Automatic

	measure 'Current Sprint End Date' = MAX(SWITCH(TRUE(), MIN('FINAL_PLC_JIRA_DATA'[Sprint Start Date]) = 'FINAL_PLC_JIRA_DATA'[Current Sprint Start Date], MIN('FINAL_PLC_JIRA_DATA'[Sprint End Date])))
		lineageTag: 6dbecea9-1ec1-f24e-3790-80bbf275d8ec

		annotation SummarizationSetBy = Automatic

	measure 'Global Story Points' = SWITCH(TRUE(), MIN('FINAL_PLC_JIRA_DATA'[Region (group)]) = "Global", MIN('FINAL_PLC_JIRA_DATA'[Story Points]), 0)
		lineageTag: bd817651-b837-f1ed-0fbb-336084c8a64c

		annotation SummarizationSetBy = Automatic

	column 'Year-Trunc of Created' = DATE(YEAR([Created]), 1, 1)
		dataType: dateTime
		lineageTag: 8f7d5e98-07a4-0879-b6ec-3446c2470c9a
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Quarter of Created' = DATE(YEAR([Created]), (QUARTER([Created])-1)*3+1, 1)
		dataType: dateTime
		lineageTag: 690ce928-043e-243a-6a15-f6355b9b2751
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Month of Created' = DATE(YEAR([Created]), MONTH([Created]), 1)
		dataType: dateTime
		lineageTag: e1d845dd-62c5-412e-18f8-35b287845f69
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Month Number of Created' = MONTH([Created])
		dataType: int64
		lineageTag: 6bfb742c-4967-1f6c-8a68-fe5d1805c4bf
		summarizeBy: none
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Year of Created' = YEAR([Created])
		dataType: int64
		lineageTag: 160396e0-496c-40d7-458c-bad2a8957292
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quarter of Created' = "Qtr " & ROUNDUP(MONTH([Created]) / 3, 0)
		dataType: string
		lineageTag: 540225c0-ebf6-5434-2e78-b72c4d5c4524
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month of Created' = FORMAT([Created], "MMMM")
		dataType: string
		lineageTag: bdc2515e-6f90-5804-6879-d160cffb6032
		summarizeBy: none
		sortByColumn: 'Month Number of Created'

		annotation SummarizationSetBy = Automatic

	column 'Day of Created' = DAY([Created])
		dataType: int64
		lineageTag: ce733bf2-d1cd-2b48-e906-5d08597fe99e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Created Hierarchy'
		lineageTag: ea085bd1-4718-057f-8970-d179dc3ca91e

		level Year
			lineageTag: c6b01c10-2ad1-7bf5-5ce2-8dfebb7bd5cf
			column: 'Year of Created'

		level Quarter
			lineageTag: 21b35927-4414-57e9-c202-1f7e1c994b64
			column: 'Quarter of Created'

		level Month
			lineageTag: ca819f6a-78e6-c1e1-2cdb-560e059661f7
			column: 'Month of Created'

		level Day
			lineageTag: d0d884e6-7bd0-6a4d-12e2-7d7866085b1d
			column: 'Day of Created'

	column 'Year-Trunc of Created Date' = DATE(YEAR([Created Date]), 1, 1)
		dataType: dateTime
		lineageTag: 3b4bd9ee-06cd-3aaa-883a-f08944e6909e
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Quarter of Created Date' = DATE(YEAR([Created Date]), (QUARTER([Created Date])-1)*3+1, 1)
		dataType: dateTime
		lineageTag: bfb3d8c6-5184-2c88-5e61-58965e14b2a0
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Month of Created Date' = DATE(YEAR([Created Date]), MONTH([Created Date]), 1)
		dataType: dateTime
		lineageTag: 2685c8f6-b949-18cf-bb10-4459485bd8c8
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Month Number of Created Date' = MONTH([Created Date])
		dataType: int64
		lineageTag: 5098caab-f72f-bbed-6a87-289f5b0bd431
		summarizeBy: none
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Year of Created Date' = YEAR([Created Date])
		dataType: int64
		lineageTag: 37d225ae-038a-f464-02cb-0cf541cf9fc6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quarter of Created Date' = "Qtr " & ROUNDUP(MONTH([Created Date]) / 3, 0)
		dataType: string
		lineageTag: e2d384e5-c32d-5a7d-cfba-ea4820be3d82
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month of Created Date' = FORMAT([Created Date], "MMMM")
		dataType: string
		lineageTag: 9c88711d-c4fb-e7e4-7539-6f26315f57c1
		summarizeBy: none
		sortByColumn: 'Month Number of Created Date'

		annotation SummarizationSetBy = Automatic

	column 'Day of Created Date' = DAY([Created Date])
		dataType: int64
		lineageTag: ee32c7db-f091-367c-ae33-84eebff53740
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Created Date Hierarchy'
		lineageTag: 5d7ffcf6-035d-64a6-4810-e624c2ea3539

		level Year
			lineageTag: 78e3ea17-80bb-31cf-f745-998ee21e80b2
			column: 'Year of Created Date'

		level Quarter
			lineageTag: d01a458d-083e-2c6f-3c0a-2d9ddb669f5a
			column: 'Quarter of Created Date'

		level Month
			lineageTag: f2db9705-eb6c-a59f-3fcd-0dbacd2888e7
			column: 'Month of Created Date'

		level Day
			lineageTag: 8a83d000-d68a-7525-825c-8512bedceebc
			column: 'Day of Created Date'

	column 'Year-Trunc of Sprint End Date' = DATE(YEAR([Sprint End Date]), 1, 1)
		dataType: dateTime
		lineageTag: e06056c2-bb17-8b6b-fe96-4793d68528a9
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Quarter of Sprint End Date' = DATE(YEAR([Sprint End Date]), (QUARTER([Sprint End Date])-1)*3+1, 1)
		dataType: dateTime
		lineageTag: 9d590c0f-342a-925a-445d-46c5fd540747
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Month of Sprint End Date' = DATE(YEAR([Sprint End Date]), MONTH([Sprint End Date]), 1)
		dataType: dateTime
		lineageTag: d9cc0f07-1d34-4f79-f748-f4a28eebfe47
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Month Number of Sprint End Date' = MONTH([Sprint End Date])
		dataType: int64
		lineageTag: 15448ca6-1cd9-5f46-a933-28f1489d3c78
		summarizeBy: none
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Year of Sprint End Date' = YEAR([Sprint End Date])
		dataType: int64
		lineageTag: 373a79d0-f1c2-998f-368c-71b2f992009c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quarter of Sprint End Date' = "Qtr " & ROUNDUP(MONTH([Sprint End Date]) / 3, 0)
		dataType: string
		lineageTag: 62f403fc-6f08-8718-9a07-ad69d3d09f08
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month of Sprint End Date' = FORMAT([Sprint End Date], "MMMM")
		dataType: string
		lineageTag: 918adeef-4e79-f8da-93c6-d4ad12a18ed1
		summarizeBy: none
		sortByColumn: 'Month Number of Sprint End Date'

		annotation SummarizationSetBy = Automatic

	column 'Day of Sprint End Date' = DAY([Sprint End Date])
		dataType: int64
		lineageTag: 41a78137-bd86-0d16-98a2-de4c8ae25bd6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Sprint End Date Hierarchy'
		lineageTag: 71657b17-e036-3ba6-8cc1-45e6430b7b83

		level Year
			lineageTag: ae14a50e-aa4a-4aaf-83f6-b9761af2931f
			column: 'Year of Sprint End Date'

		level Quarter
			lineageTag: 50b584a5-a0f1-dfd9-8696-32fd19fb62f0
			column: 'Quarter of Sprint End Date'

		level Month
			lineageTag: c222be31-39fe-bb05-0c62-5f848e4860aa
			column: 'Month of Sprint End Date'

		level Day
			lineageTag: 391d5c07-8f10-5b17-e60b-ea1d50b224e6
			column: 'Day of Sprint End Date'

	column 'Year-Trunc of Sprint Start Date' = DATE(YEAR([Sprint Start Date]), 1, 1)
		dataType: dateTime
		lineageTag: 7e221997-5f19-1268-c7ff-9e6506dc3ab6
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Quarter of Sprint Start Date' = DATE(YEAR([Sprint Start Date]), (QUARTER([Sprint Start Date])-1)*3+1, 1)
		dataType: dateTime
		lineageTag: 4a2bdfe7-e915-4c4c-80d2-11ec828043e6
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Month of Sprint Start Date' = DATE(YEAR([Sprint Start Date]), MONTH([Sprint Start Date]), 1)
		dataType: dateTime
		lineageTag: d331948c-639c-d3da-8adf-1b08734ce35f
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Month Number of Sprint Start Date' = MONTH([Sprint Start Date])
		dataType: int64
		lineageTag: b96b7437-3b94-c4b1-61e7-fcb4b8544fb6
		summarizeBy: none
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Year of Sprint Start Date' = YEAR([Sprint Start Date])
		dataType: int64
		lineageTag: 4a7d6b0b-6cd6-ad25-39f0-584a16152228
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quarter of Sprint Start Date' = "Qtr " & ROUNDUP(MONTH([Sprint Start Date]) / 3, 0)
		dataType: string
		lineageTag: aa713595-b1be-9c4a-906c-4e3552e263f4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month of Sprint Start Date' = FORMAT([Sprint Start Date], "MMMM")
		dataType: string
		lineageTag: 70cee32f-e321-d3cd-8073-7f435dbf5960
		summarizeBy: none
		sortByColumn: 'Month Number of Sprint Start Date'

		annotation SummarizationSetBy = Automatic

	column 'Day of Sprint Start Date' = DAY([Sprint Start Date])
		dataType: int64
		lineageTag: d7f0cf8b-1128-64c6-6989-813b9f131d4a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Sprint Start Date Hierarchy'
		lineageTag: bfde002e-4e8d-7c02-df6b-24130fdecaa6

		level Year
			lineageTag: c715d1f7-5101-be12-0d5b-e0408387ed2f
			column: 'Year of Sprint Start Date'

		level Quarter
			lineageTag: 8da19ec2-6125-8b3f-958f-e5bb620fc7d9
			column: 'Quarter of Sprint Start Date'

		level Month
			lineageTag: b7cb32dc-e66f-53a1-1305-bb5874f58403
			column: 'Month of Sprint Start Date'

		level Day
			lineageTag: d8d9ac2f-8b1e-3a4f-d248-2ead81b545b9
			column: 'Day of Sprint Start Date'

	column 'Year-Trunc of Status Category Changed' = DATE(YEAR([Status Category Changed]), 1, 1)
		dataType: dateTime
		lineageTag: cacf11b4-af15-b4fa-e353-ee2edc1d5ce9
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Quarter of Status Category Changed' = DATE(YEAR([Status Category Changed]), (QUARTER([Status Category Changed])-1)*3+1, 1)
		dataType: dateTime
		lineageTag: 89fe489c-8844-8929-8a8e-bfd00d8d69b3
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Month of Status Category Changed' = DATE(YEAR([Status Category Changed]), MONTH([Status Category Changed]), 1)
		dataType: dateTime
		lineageTag: 8bbec201-e0d6-0ebb-c388-c95b9c8b0a11
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Month Number of Status Category Changed' = MONTH([Status Category Changed])
		dataType: int64
		lineageTag: 2572e077-8bd5-6c08-8f25-63a90d19dd8d
		summarizeBy: none
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Year of Status Category Changed' = YEAR([Status Category Changed])
		dataType: int64
		lineageTag: 0d4f99d5-a1b6-8c17-e861-bb80b7e03e0a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quarter of Status Category Changed' = "Qtr " & ROUNDUP(MONTH([Status Category Changed]) / 3, 0)
		dataType: string
		lineageTag: 27d8a910-5cb0-1363-5924-1ba85dfbf09c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month of Status Category Changed' = FORMAT([Status Category Changed], "MMMM")
		dataType: string
		lineageTag: 43b77930-bee1-745d-5a63-2bf16a714203
		summarizeBy: none
		sortByColumn: 'Month Number of Status Category Changed'

		annotation SummarizationSetBy = Automatic

	column 'Day of Status Category Changed' = DAY([Status Category Changed])
		dataType: int64
		lineageTag: 21460bf1-c1ff-165b-0972-5a35f76b60fd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Status Category Changed Hierarchy'
		lineageTag: 1753c69d-a71f-c879-c590-0219d721830c

		level Year
			lineageTag: a134f859-cba7-abf0-4bd4-d219e7ef2f6b
			column: 'Year of Status Category Changed'

		level Quarter
			lineageTag: b78479f3-2ede-69ee-75ce-b0e0f914fa00
			column: 'Quarter of Status Category Changed'

		level Month
			lineageTag: f948148e-1bd6-93bc-91e0-b61385f2204d
			column: 'Month of Status Category Changed'

		level Day
			lineageTag: 3481fdcc-07f6-62b1-693c-6665ff46198e
			column: 'Day of Status Category Changed'

	column 'Year-Trunc of Updated' = DATE(YEAR([Updated]), 1, 1)
		dataType: dateTime
		lineageTag: f22f5b11-092a-eb17-20ba-54d53f6acdc6
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Quarter of Updated' = DATE(YEAR([Updated]), (QUARTER([Updated])-1)*3+1, 1)
		dataType: dateTime
		lineageTag: 364daecc-a245-b399-55c7-d8dcf79e5c12
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Year-Month of Updated' = DATE(YEAR([Updated]), MONTH([Updated]), 1)
		dataType: dateTime
		lineageTag: 04ae6396-19de-c99b-9d4a-81ea5ec4cf76
		summarizeBy: none
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column 'Month Number of Updated' = MONTH([Updated])
		dataType: int64
		lineageTag: fb6af281-174c-920a-f45a-e855c822481a
		summarizeBy: none
		isHidden

		annotation SummarizationSetBy = Automatic

	column 'Year of Updated' = YEAR([Updated])
		dataType: int64
		lineageTag: 70f92462-a806-486d-9b58-f12896a27d82
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quarter of Updated' = "Qtr " & ROUNDUP(MONTH([Updated]) / 3, 0)
		dataType: string
		lineageTag: af31a591-468c-4c2f-f502-51d6ef7a2a9d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month of Updated' = FORMAT([Updated], "MMMM")
		dataType: string
		lineageTag: 9f4b3106-9d74-8a12-c2d9-dc9c59c82b57
		summarizeBy: none
		sortByColumn: 'Month Number of Updated'

		annotation SummarizationSetBy = Automatic

	column 'Day of Updated' = DAY([Updated])
		dataType: int64
		lineageTag: ce275f29-e11c-8f87-d8a7-22e4c8a3bc3d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Updated Hierarchy'
		lineageTag: 8c8f82fa-1088-fd90-6386-9731e32d00b4

		level Year
			lineageTag: 73aff76b-5f50-911d-ffbe-01505ba903f5
			column: 'Year of Updated'

		level Quarter
			lineageTag: e909df13-1dc6-746d-a62e-c3c1174d0639
			column: 'Quarter of Updated'

		level Month
			lineageTag: b25d3b88-0937-153a-8ec8-553f3160129b
			column: 'Month of Updated'

		level Day
			lineageTag: 18fd2c62-459c-8c7a-2a2f-4c27bf6c7dd2
			column: 'Day of Updated'

	partition FINAL_PLC_JIRA_DATA = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents("C:\Users\ShrikantPansare\Downloads\Agent Version 0511_ABCD\Agent Version 0511_ABCD\_workspace\Sprint_test_pbip\Sprint Output.SemanticModel\data\federated.116u3w61hxzxmf1egxq6w1raicvd\Extract.Extract.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"CATEGORY", type text}, {"SUMMARY", type text}, {"STORY_POINTS", Int64.Type}, {"ISSUE_KEY", type text}, {"REGION", type text}, {"ENVIRONMENT", type text}, {"STATUS", type text}, {"PRIORITY", type text}, {"ASSIGNEE", type text}, {"UPDATED", type datetime}, {"SPRINT", type text}, {"EPIC", type text}, {"TEAM", type text}, {"SPRINT_START_DATE", type datetime}, {"SPRINT_END_DATE", type datetime}, {"ROLLOVER_FLAG", type text}})
			in
			    ChangedTypes

	annotation PBI_ResultType = Table
