table 'Order By :'
	lineageTag: 8f0b599d-bb63-aa5a-28fb-c52186490dbc

	column Value
		dataType: string
		lineageTag: 3aab2e2c-0966-3650-1ff2-73454f42657c
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Label
		dataType: string
		lineageTag: 84b4f6fe-17ff-57f9-4cfc-8344daee4114
		summarizeBy: none
		sourceColumn: Label

		annotation SummarizationSetBy = Automatic

	partition 'Order By :' = m
		mode: import
		source =
			let
			    Source = Table.FromRows({{"Ascending", "Ascending"}, {"Descending", "Descending"}}, type table [#"Value" = text, #"Label" = text])
			in
			    Source

	annotation PBI_ResultType = Table
