table 'Ticket Type'
	lineageTag: beae88ac-143b-2374-0c6b-9f77e251beb0

	column Value
		dataType: string
		lineageTag: a012605a-7181-0e69-5fea-0012d6994ff1
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Label
		dataType: string
		lineageTag: 2b99ca17-ffdf-4a93-2055-474bf67994a4
		summarizeBy: none
		sourceColumn: Label

		annotation SummarizationSetBy = Automatic

	partition 'Ticket Type' = m
		mode: import
		source =
			let
			    Source = Table.FromRows({{"Total", "Total"}, {"Rollover", "Rollover"}, {"Assigned", "Assigned"}, {"Unassigned", "Unassigned"}}, type table [#"Value" = text, #"Label" = text])
			in
			    Source

	annotation PBI_ResultType = Table
