table dim_hcp
	lineageTag: e6b13c76-3520-8b62-b294-64160e0efc9f

	column 'Address Line1'
		dataType: string
		lineageTag: d2dff5f6-ab51-b4af-a900-0b815d94e181
		summarizeBy: none
		sourceColumn: Address_Line1

		annotation SummarizationSetBy = Automatic

	column 'Bridge Score'
		dataType: double
		lineageTag: 66150008-0320-fd23-bf30-dee92dcf2669
		summarizeBy: sum
		sourceColumn: Bridge_Score

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 77e17226-28a4-e58b-66f1-a942d1bd2cc3
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Cluster ID'
		dataType: int64
		lineageTag: e62ad6d7-64fc-48ea-6253-89c493f19f92
		summarizeBy: none
		sourceColumn: Cluster_ID

		annotation SummarizationSetBy = Automatic

	column 'Eigenvector Score'
		dataType: double
		lineageTag: c8a6c400-8f56-e30f-4940-000e4fce75dd
		summarizeBy: sum
		sourceColumn: Eigenvector_Score

		annotation SummarizationSetBy = Automatic

	column 'Final Segment'
		dataType: string
		lineageTag: 3e45f8cb-e5d4-5f63-4f19-fddb58a077bc
		summarizeBy: none
		sourceColumn: Final_Segment

		annotation SummarizationSetBy = Automatic

	column 'Hco Id'
		dataType: int64
		lineageTag: f3e17464-61ff-5e6e-cf3d-7a1a7e27955b
		summarizeBy: none
		sourceColumn: HCO_ID

		annotation SummarizationSetBy = Automatic

	column 'Hcp Id'
		dataType: int64
		lineageTag: d71cfded-b24f-f0a5-7b41-5405788809f9
		summarizeBy: none
		sourceColumn: HCP_ID

		annotation SummarizationSetBy = Automatic

	column 'HCP Name'
		dataType: string
		lineageTag: c635664e-88a8-7f74-4bdc-fd001afcf71d
		summarizeBy: none
		sourceColumn: HCP_Name

		annotation SummarizationSetBy = Automatic

	column 'Incoming Referrals'
		dataType: int64
		lineageTag: f049f2ed-6f29-2f81-6b49-2ba338f97636
		summarizeBy: sum
		sourceColumn: Incoming_Referrals

		annotation SummarizationSetBy = Automatic

	column 'Influence Score'
		dataType: double
		lineageTag: 44a791e3-4b4e-aa16-c546-f3a1f16b6d82
		summarizeBy: sum
		sourceColumn: Influence_Score

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 247bf3c1-2a7d-b4f0-5472-009d742226d3
		summarizeBy: none
		sourceColumn: Latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		lineageTag: 3723d9ce-6bb8-661d-af87-8d6f33008749
		summarizeBy: none
		sourceColumn: Longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column 'Mistreated Patients'
		dataType: int64
		lineageTag: fa499c16-c61f-04d2-5d24-29b3e2f6876f
		summarizeBy: sum
		sourceColumn: Mistreated_Patients

		annotation SummarizationSetBy = Automatic

	column 'Outgoing Referrals'
		dataType: int64
		lineageTag: 93905e4f-c2ad-7fa5-4ea0-c1ab727594e7
		summarizeBy: sum
		sourceColumn: Outgoing_Referrals

		annotation SummarizationSetBy = Automatic

	column 'Patients Count'
		dataType: int64
		lineageTag: c3ca5efc-ea86-91a7-4732-e0f42505dd81
		summarizeBy: sum
		sourceColumn: Patients_Count

		annotation SummarizationSetBy = Automatic

	column 'Patients Diagnosed'
		dataType: int64
		lineageTag: a2a4cb57-9bc9-bfbc-f65a-4c69b91fda55
		summarizeBy: sum
		sourceColumn: Patients_Diagnosed

		annotation SummarizationSetBy = Automatic

	column 'Patients Prescribed'
		dataType: int64
		lineageTag: 4efd9756-94a8-9464-d05d-0c07cabf4d94
		summarizeBy: sum
		sourceColumn: Patients_Prescribed

		annotation SummarizationSetBy = Automatic

	column 'Patients Treated'
		dataType: int64
		lineageTag: b492a0d9-942c-5469-f366-916998ca61e0
		summarizeBy: sum
		sourceColumn: Patients_Treated

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 66cdc466-9414-7fe8-b161-73b80c3be1eb
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Specialty
		dataType: string
		lineageTag: 28752961-f13c-d253-da5e-0c9e1c12eede
		summarizeBy: none
		sourceColumn: Specialty

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: c5ca5342-0595-80c3-c4db-46e16f98c4fd
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Territory Name'
		dataType: string
		lineageTag: d21baa2c-9ec8-70cf-f094-e43c31195837
		summarizeBy: none
		sourceColumn: Territory_Name

		annotation SummarizationSetBy = Automatic

	column ZIP
		dataType: int64
		lineageTag: 9881e0da-62ec-bd4f-c7c0-c193b97e703f
		summarizeBy: none
		sourceColumn: ZIP

		annotation SummarizationSetBy = Automatic

	column Affiliation
		dataType: string
		lineageTag: fca1f5aa-04e4-ffab-daec-979c556d2915
		summarizeBy: none
		sourceColumn: Affiliation

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: aa7b59ba-d23c-fcad-510f-4e471ae28283
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: ba005c3d-1f5d-4ae4-47ac-a5b13c820e82
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column 'Specialty (group)' = SWITCH(TRUE(), [Specialty] IN { "NP/PA", "Other Non-Specialists", "Other Specialists" }, "Others", [Specialty] IN { "Psychiatrist", "Psychologist" }, "Psychiatrist", [Specialty] )
		dataType: string
		lineageTag: 0d0572b8-aae1-fc3b-7dd6-7d9e7b22a02e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	measure 'Sum of Patients' = SUM('dim_hco'[Patients Count (dim hco)])
		lineageTag: ef48c430-7555-cbf0-7173-e73c58cdb2a8

		annotation SummarizationSetBy = Automatic

	measure 'Total Territories' = DISTINCTCOUNT('dim_hco'[Territory (dim hco)])
		lineageTag: 1956e35e-35a3-677a-04c8-a87197ea6010

		annotation SummarizationSetBy = Automatic

	partition dim_hcp = m
		mode: import
		source =
			let
			    // TODO: live connection class 'databricks' - rewire the connector in PBI Desktop
			    Source = Table.FromRows({}, type table [#"Address_Line1" = text, #"Bridge_Score" = number, #"City" = text, #"Cluster_ID" = number, #"Eigenvector_Score" = number, #"Final_Segment" = text, #"HCO_ID" = number, #"HCP_ID" = number, #"HCP_Name" = text, #"Incoming_Referrals" = number, #"Influence_Score" = number, #"Latitude" = number, #"Longitude" = number, #"Mistreated_Patients" = number, #"Outgoing_Referrals" = number, #"Patients_Count" = number, #"Patients_Diagnosed" = number, #"Patients_Prescribed" = number, #"Patients_Treated" = number, #"Region" = text, #"Specialty" = text, #"State" = text, #"Territory_Name" = text, #"ZIP" = number, #"Affiliation" = text, #"Email" = text, #"Territory" = text])
			in
			    Source

	annotation PBI_ResultType = Table
