table dim_hco
	lineageTag: c9125b98-b16a-5a01-c791-5366d1ef8d86

	column City
		dataType: string
		lineageTag: cb4852d6-a4e6-1ff9-79df-ed68dd7d464c
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Hco Id'
		dataType: int64
		lineageTag: c71f3d45-96dd-676d-c87a-58b6ae87dc7a
		summarizeBy: none
		sourceColumn: HCO_ID

		annotation SummarizationSetBy = Automatic

	column 'HCO Name'
		dataType: string
		lineageTag: bef48deb-1063-cab7-c60a-aaa26698476e
		summarizeBy: none
		sourceColumn: HCO_Name

		annotation SummarizationSetBy = Automatic

	column 'HCO Type'
		dataType: string
		lineageTag: 57bda256-1926-2373-c94b-e666f8395ac9
		summarizeBy: none
		sourceColumn: HCO_Type

		annotation SummarizationSetBy = Automatic

	column 'Incoming Referrals'
		dataType: int64
		lineageTag: f74e3afe-2041-fe68-bc2b-b2ff10fa4257
		summarizeBy: sum
		sourceColumn: Incoming_Referrals

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 2841283b-baa1-7f79-eea0-66fff760216e
		summarizeBy: none
		sourceColumn: Latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		lineageTag: 55397740-3395-8e51-f4ae-9c0222554a60
		summarizeBy: none
		sourceColumn: Longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column 'Mistreated Patients'
		dataType: int64
		lineageTag: f1e3985f-6b29-7337-0ca9-2d0aff4f9c39
		summarizeBy: sum
		sourceColumn: Mistreated_Patients

		annotation SummarizationSetBy = Automatic

	column 'Outgoing Referrals'
		dataType: int64
		lineageTag: 26320774-02d1-5395-9471-37f270c80a52
		summarizeBy: sum
		sourceColumn: Outgoing_Referrals

		annotation SummarizationSetBy = Automatic

	column 'Patients Count'
		dataType: int64
		lineageTag: f1e2b437-1014-9108-30e5-e5980bfdef47
		summarizeBy: sum
		sourceColumn: Patients_Count

		annotation SummarizationSetBy = Automatic

	column 'Patients Diagnosed'
		dataType: int64
		lineageTag: b20b43bb-c3fe-bc3e-5af0-76a712b08eea
		summarizeBy: sum
		sourceColumn: Patients_Diagnosed

		annotation SummarizationSetBy = Automatic

	column 'Patients Prescribed'
		dataType: int64
		lineageTag: 7ca0073a-2bd0-1694-5cb9-4aab91a00107
		summarizeBy: sum
		sourceColumn: Patients_Prescribed

		annotation SummarizationSetBy = Automatic

	column 'Patients Treated'
		dataType: int64
		lineageTag: 0a1845e8-b821-e357-064c-78967336c73f
		summarizeBy: sum
		sourceColumn: Patients_Treated

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: af7f943d-8a5a-1f30-a90c-dcd003b6a061
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 1d660019-f675-ab66-ef70-e6822c5fe43e
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Territory Name'
		dataType: string
		lineageTag: f240f794-3b17-665b-cc36-bb29d014196f
		summarizeBy: none
		sourceColumn: Territory_Name

		annotation SummarizationSetBy = Automatic

	column 'Total HCPs'
		dataType: int64
		lineageTag: c4257e76-a245-534d-a797-2d288a96b717
		summarizeBy: sum
		sourceColumn: Total_HCPs

		annotation SummarizationSetBy = Automatic

	column ZIP
		dataType: int64
		lineageTag: 719a8d84-aa52-ea2d-f84f-4b6b2c0b4da1
		summarizeBy: none
		sourceColumn: ZIP

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: 7bc35079-4057-b2a4-e932-49dc3016b918
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 57f149b4-13c5-4217-c561-25f4d382cdf5
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	measure 'Sum of Patients' = SUM('dim_hco'[Patients Count])
		lineageTag: 21814829-206d-4c1e-a373-35e01f7f8704

		annotation SummarizationSetBy = Automatic

	measure 'Total Territories' = DISTINCTCOUNT('dim_hco'[Territory])
		lineageTag: 18c76a9e-d034-3037-ec88-031a465b8916

		annotation SummarizationSetBy = Automatic

	partition dim_hco = m
		mode: import
		source =
			let
			    ExtractFilterSource =
			        let
			            Source = DatabricksMultiCloud.Catalogs("dbc-3ee0f24b-247b.cloud.databricks.com", "/sql/1.0/warehouses/2be996b7370ad54a", [Catalog="", Database="", QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation="2.0"]),
			            Catalog = Source{[Name="turbobi", Kind="Database"]}[Data],
			            Schema = Catalog{[Name="takeda", Kind="Schema"]}[Data],
			            Navigation = Schema{[Name="dim_hco", Kind="Table"]}[Data]
			        in
			            Navigation,
			    FilteredRows = Table.SelectRows(ExtractFilterSource, each (List.Contains({"Midwest"}, [#"Region"])))
			in
			    FilteredRows

	annotation PBI_ResultType = Table
