"""Parser for the `qlik app unbuild` output folder.

The Qlik CLI emits this layout (see config.yml in the output dir):

    output/
      app-properties.json
      config.yml
      connections.yml
      script.qvs
      dimensions.json        - master dimensions (library items)
      measures.json          - master measures (library items)
      variables.json         - script + UI variables
      objects/
        sheet--<title>-<guid>.json
        masterobject-<title>-<guid>.json
        appprops---<guid>.json
        loadmodel---loadmodel.json

This module walks that directory and returns a single IR dict the rest of
the pipeline consumes. We do not look at QVD or hyper data here - that
belongs in a future enrichment pass.
"""

import json
import re
from pathlib import Path
from typing import Any, Dict, List

from ._logging import get_logger
from .ir import QlikIR
from .script_parser import parse_field_renames, parse_db_sources
from .script_to_m import ScriptTranslator

_log = get_logger("PARSE")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def parse_qlik_output(output_dir: str | Path) -> QlikIR:
    """Read the qlik-unbuild output folder into a typed ``QlikIR``.

    The returned object exposes the same ``ir.get(key)`` / ``ir[key]``
    mapping interface the pipeline has always used (see
    :class:`qlik_to_pbi.ir.QlikIR`), so downstream stages are unchanged;
    the dataclass just makes the cross-stage contract explicit and lets
    the orchestrator release heavy raw-input slots after the model build.
    """
    root = Path(output_dir)
    if not root.exists():
        raise FileNotFoundError(f"Qlik output folder not found: {root}")

    ir: Dict[str, Any] = {
        "app":         _read_json(root / "app-properties.json", default={}),
        "script":      _read_text(root / "script.qvs"),
        "dimensions":  _read_json(root / "dimensions.json", default=[]),
        "measures":    _read_json(root / "measures.json",   default=[]),
        "variables":   _read_json(root / "variables.json",  default=[]),
        "bookmarks":   _read_json(root / "bookmarks.json",  default=[]),
        "sheets":      [],
        "master_objects": [],
        "load_model":  None,
        "app_props":   None,
        # Authoritative engine-current schema. Written by engine_fetch
        # via GetTablesAndKeys and consumed by model.py as the source
        # of truth for table layout, field-to-table mapping, and key
        # records. None when the engine path wasn't taken.
        "engine_schema": None,
    }

    objects_dir = root / "objects"
    if objects_dir.is_dir():
        for fp in sorted(objects_dir.glob("*.json")):
            obj = _read_json(fp, default=None)
            if obj is None:
                continue
            kind = _classify_object(fp.name, obj)
            if kind == "sheet":
                ir["sheets"].append(
                    _normalize_sheet(obj, filename=fp.name),
                )
            elif kind == "masterobject":
                ir["master_objects"].append(obj)
            elif kind == "loadmodel":
                ir["load_model"] = obj
            elif kind == "appprops":
                ir["app_props"] = obj
            elif kind == "engineschema":
                ir["engine_schema"] = obj

    # Sort sheets by rank if present so page order matches the Qlik
    # navigation bar.
    ir["sheets"].sort(key=lambda s: s.get("rank", 0))

    _log.info(
        f"Parsed {len(ir['sheets'])} sheets, "
        f"{len(ir['dimensions'])} dimensions, "
        f"{len(ir['measures'])} measures, "
        f"{len(ir['variables'])} variables."
    )

    # Build the field universe used to synthesise the stub table later.
    ir["fields"] = _collect_field_universe(ir)

    # Recover per-table field rename info from the script's
    # autogenerated section -- e.g. ``[HCP_ID] AS [From_HCP_ID-HCP_ID]``
    # tells us the engine field ``From_HCP_ID-HCP_ID`` was originally
    # ``HCP_ID`` on the HCP table. Used downstream to:
    #   * Label TMDL columns with the friendlier original name.
    #   * Map engine ``qk`` key records (which carry the post-script
    #     field name) to per-table relationship endpoints under the
    #     original names.
    ir["field_renames"] = parse_field_renames(ir.get("script") or "")

    # Tables loaded from a SQL data connection (LIB CONNECT TO [name] + SQL
    # SELECT ... FROM catalog.schema.table). When the user supplies that
    # connection's details, model.py repoints these tables at the live source
    # (e.g. a Databricks Import partition) instead of binding the engine-loaded
    # snapshot. {} for pure file/QVD apps.
    ir["db_sources"] = parse_db_sources(ir.get("script") or "")

    # Script-derived LOAD blocks. Each block carries a ready-to-use
    # Power Query M expression for one source table (Csv.Document /
    # Excel.Workbook / Qvd.Tables / Folder.Files / Sql.Database / ...).
    # The model.py partition emitter consumes these when no CSV is
    # bound and no live-DB credentials match, so the PBIP carries
    # real partitions instead of empty stubs.
    var_lookup: Dict[str, str] = {}
    for v in ir.get("variables") or []:
        vn = (v.get("qName") or "").strip()
        vd = v.get("qDefinition")
        if vn and isinstance(vd, str):
            var_lookup[vn] = vd
    try:
        script_blocks = ScriptTranslator(variables=var_lookup).parse_blocks(
            ir.get("script") or "",
        )
        ir["script_blocks"] = [
            {
                "table":         b.table_name,
                "fields":        b.fields,
                "source":        b.source,
                "source_type":   b.source_type,
                "join_type":     b.join_type,
                "is_concatenate": b.is_concatenate,
                "m_expression":  b.m_expression,
                "notes":         b.notes,
            }
            for b in script_blocks
        ]
        _log.info(
            f"Script-derived load blocks: {len(ir['script_blocks'])} "
            "(usable as partition M when no CSV / live-DB match)."
        )
    except Exception as exc:  # noqa: BLE001 -- best-effort
        _log.warning(f"Could not parse script LOAD blocks: {exc}")
        ir["script_blocks"] = []

    # Hand the rest of the pipeline a typed object rather than a bare
    # dict. ``QlikIR`` preserves the mapping interface, so every
    # downstream ``ir.get(...)`` call site is unchanged.
    return QlikIR.from_dict(ir)


# ---------------------------------------------------------------------------
# Per-file readers
# ---------------------------------------------------------------------------

def _read_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError) as exc:
        _log.warning(f"Could not parse {path.name}: {exc}")
        return default


def _read_text(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except OSError:
        return ""


def _classify_object(filename: str, obj: Dict[str, Any]) -> str:
    """Return one of `sheet | masterobject | loadmodel | appprops |
    engineschema | other`."""
    name = filename.lower()
    if name.startswith("sheet--") or name.startswith("sheet-"):
        return "sheet"
    if name.startswith("masterobject"):
        return "masterobject"
    if name.startswith("loadmodel"):
        return "loadmodel"
    if name.startswith("appprops"):
        return "appprops"
    if name == "engine-schema.json":
        return "engineschema"
    q_type = (obj.get("qInfo", {}) or {}).get("qType", "")
    return q_type or "other"


# ---------------------------------------------------------------------------
# Sheet flattening
# ---------------------------------------------------------------------------

def _normalize_sheet(obj: Dict[str, Any], filename: str = "") -> Dict[str, Any]:
    """Flatten a sheet object into something the report builder can iterate.

    Each cell in `cells` gets its corresponding `qChildren[i].qProperty`
    inlined under `properties`, indexed by the cell's `name`.

    Page title resolution priority:
      1. ``qMetaDef.title`` - what the user typed in the sheet.
      2. The slug embedded in the filename
         ``sheet--<title-kebab>-<guid>.json``.
      3. Literal ``"Untitled"``.
    """
    prop = obj.get("qProperty", {}) or {}
    info = prop.get("qInfo", {}) or {}
    meta = prop.get("qMetaDef", {}) or {}

    title = (meta.get("title") or "").strip()
    if not title and filename:
        title = _title_from_filename(filename)
    if not title:
        title = "Untitled"

    # children_by_id keys every child node (recursively) by its qId so
    # cells that reference a deeply-nested child (e.g. a filterpane
    # whose listbox grandchildren carry the actual field bindings) can
    # still be reached. children_subtree_by_id preserves the full
    # subtree (qProperty + qChildren) so downstream code can iterate
    # the children of a container cell.
    children_by_id: Dict[str, Dict[str, Any]] = {}
    children_subtree_by_id: Dict[str, Dict[str, Any]] = {}

    def _index_subtree(node: Dict[str, Any]) -> None:
        c_prop = node.get("qProperty", {}) or {}
        c_id = (c_prop.get("qInfo", {}) or {}).get("qId", "")
        if c_id:
            children_by_id[c_id] = c_prop
            children_subtree_by_id[c_id] = node
        for grandchild in node.get("qChildren", []) or []:
            _index_subtree(grandchild)

    for child in obj.get("qChildren", []) or []:
        _index_subtree(child)

    cells = []
    for cell in prop.get("cells", []) or []:
        cell_id = cell.get("name", "")
        subtree = children_subtree_by_id.get(cell_id) or {}
        # Extract the immediate child q-properties so the report
        # builder can walk filterpane->listbox grandchildren without
        # re-traversing the raw JSON shape.
        child_nodes: List[Dict[str, Any]] = list(subtree.get("qChildren") or [])
        child_props: List[Dict[str, Any]] = [
            (gc.get("qProperty") or {}) for gc in child_nodes
        ]
        cells.append({
            **cell,
            "properties":     children_by_id.get(cell_id, {}),
            "child_children": child_props,
            # Full child subtrees ({qProperty, qChildren}) so a CONTAINER
            # cell can hand each child its OWN children -- e.g. a filterpane
            # inside a container keeps its listboxes (-> real slicers) rather
            # than collapsing to a placeholder. child_children stays the
            # flat qProperty list the filterpane builder already consumes.
            "child_nodes":    child_nodes,
        })

    return {
        "id":          info.get("qId", ""),
        "title":       title,
        "description": meta.get("description", ""),
        "rank":        prop.get("rank", 0),
        "columns":     prop.get("columns", 24),
        "rows":        prop.get("rows", 12),
        "cells":       cells,
    }


_SHEET_FILENAME_RE = re.compile(
    r"^sheet--(?P<slug>.+?)-"
    r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
    r"\.json$",
    re.IGNORECASE,
)


def _title_from_filename(filename: str) -> str:
    """Extract the title slug from `sheet--<slug>-<guid>.json`.

    Qlik names the unbuilt sheet file with the GUID at the end after a
    final hyphen, and the title slug between the first `--` and that
    GUID. Returns the slug with hyphens turned into spaces and the
    first letter of each word capitalised.
    """
    m = _SHEET_FILENAME_RE.match(filename)
    if not m:
        return ""
    slug = m.group("slug").replace("-", " ").strip()
    if not slug:
        return ""
    return " ".join(w.capitalize() for w in slug.split())


# ---------------------------------------------------------------------------
# Field universe
# ---------------------------------------------------------------------------

_FIELD_REF_RE = re.compile(r"\[([^\[\]\r\n]{1,80})\]")
_BARE_FIELD_RE = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]{1,60})\b")


def _collect_field_universe(ir: Dict[str, Any]) -> List[str]:
    """Pull every field name referenced anywhere into a sorted unique list.

    Used by `model.py` to populate the stub fact table so visuals have
    valid columns to bind to. We intentionally over-collect: PBI ignores
    unused columns at load time but rejects bindings to columns it never
    saw.
    """
    seen: Dict[str, None] = {}

    def add(name: str) -> None:
        n = (name or "").strip()
        if not n or n.startswith("$"):
            return
        if len(n) > 80:
            return
        seen.setdefault(n, None)

    def add_from_text(text: str) -> None:
        if not text:
            return
        for m in _FIELD_REF_RE.findall(text):
            add(m)

    # Dimensions
    for d in ir.get("dimensions", []) or []:
        defs = (d.get("qDim", {}) or {}).get("qFieldDefs", []) or []
        for fd in defs:
            # Field defs may be `Field`, `[Field]`, or `=expression`.
            if fd.startswith("="):
                add_from_text(fd)
            else:
                add(fd.strip("[]"))

    # Measures and variables - expressions are full of field references.
    for m in ir.get("measures", []) or []:
        add_from_text((m.get("qMeasure", {}) or {}).get("qDef", ""))

    for v in ir.get("variables", []) or []:
        add_from_text(v.get("qDefinition", ""))

    # Sheets - look at the dim/measure libraryIds and any inline qFieldDefs.
    for sheet in ir.get("sheets", []) or []:
        for cell in sheet.get("cells", []) or []:
            _harvest_hypercube_fields(cell.get("properties", {}), add, add_from_text)

    for mobj in ir.get("master_objects", []) or []:
        _harvest_hypercube_fields(mobj, add, add_from_text)

    return sorted(seen.keys(), key=lambda x: x.lower())


def _harvest_hypercube_fields(node: Any, add, add_from_text) -> None:
    """Recursively pull qFieldDefs out of any nested qHyperCubeDef."""
    if isinstance(node, dict):
        if "qFieldDefs" in node:
            for fd in node.get("qFieldDefs", []) or []:
                if isinstance(fd, str):
                    if fd.startswith("="):
                        add_from_text(fd)
                    else:
                        add(fd.strip("[]"))
        if "qDef" in node and isinstance(node["qDef"], str):
            add_from_text(node["qDef"])
        for v in node.values():
            _harvest_hypercube_fields(v, add, add_from_text)
    elif isinstance(node, list):
        for v in node:
            _harvest_hypercube_fields(v, add, add_from_text)
