"""Qlik load-script parser for per-table field rename recovery.

The Qlik Data Manager's autogenerated section routinely renames
source fields via patterns like::

    [Referral Edge_temp_<guid>]:
    LOAD
        [Link_ID],
        [From_HCP_ID] AS [From_HCP_ID-HCP_ID],
        [To_HCP_ID],
        ...
    RESIDENT [Referral Edge];

    [HCP_temp_<guid>]:
    LOAD
        [HCP_ID] AS [From_HCP_ID-HCP_ID],
        ...
    RESIDENT [HCP];

    RENAME TABLE [Referral Edge_temp_<guid>] to [Referral Edge];
    RENAME TABLE [HCP_temp_<guid>]           to [HCP];

The engine field-list (``GetTablesAndKeys``) reflects the POST-script
state -- both tables now carry a field literally named
``From_HCP_ID-HCP_ID``. We don't want that name as the final TMDL
column heading: it should appear as ``From_HCP_ID`` on Referral Edge
(its original semantic source) and as ``HCP_ID`` on HCP (likewise).

This module recovers the per-table rename map from the script so the
PBIP can:

  * Use the friendlier original name as the TMDL column heading.
  * Translate ``qk`` engine key records (which name the post-script
    field) into relationships whose endpoints carry the per-table
    original-name labels.

The parser focuses on the autogenerated section's simple
``[Source] AS [Target]`` patterns. Computed expressions
(``GeoMakePoint(...) AS [Foo]``, ``APPLYMAP(...) AS [Bar]``) have no
source field to recover; we record them as identity mappings so the
engine name is preserved verbatim.
"""

from __future__ import annotations

import re
from typing import Dict, List

from ._logging import get_logger

_log = get_logger("SCRIPT")


# Walks every `[TableName]: LOAD ... RESIDENT|FROM ...;` block. The
# table label can be a bare identifier or bracket-wrapped; the body is
# everything between LOAD and the source clause.
_LOAD_BLOCK_RE = re.compile(
    r"(?:^|;|\n)\s*"
    r"\[?(?P<tname>[A-Za-z_][^\]\[\n;:]{0,200}?)\]?"
    r"\s*:\s*"
    r"LOAD\b\s*"
    r"(?P<body>[\s\S]+?)"
    r"\s+(?:RESIDENT|FROM)\b",
    re.IGNORECASE,
)

# `RENAME TABLE [A] to [B];`. Both sides may or may not be bracketed.
_RENAME_RE = re.compile(
    r"RENAME\s+TABLE\s+"
    r"\[?(?P<src>[^\]\[;\n]+?)\]?\s+"
    r"to\s+"
    r"\[?(?P<dst>[^\]\[;\n]+?)\]?"
    r"\s*;",
    re.IGNORECASE,
)

# A *simple* `[Source] AS [Target]` field def. Rejects parens so
# function-call expressions don't match.
_SIMPLE_RENAME_RE = re.compile(
    r"^\s*"
    r"(?P<src>\[[^\[\]]+\]|[A-Za-z_][A-Za-z0-9_.]*)"
    r"\s+AS\s+"
    r"(?P<tgt>\[[^\[\]]+\]|[A-Za-z_][A-Za-z0-9_.]*)"
    r"\s*$",
    re.IGNORECASE,
)

# A plain (no-rename) field def: just an identifier or bracketed name.
_PLAIN_FIELD_RE = re.compile(
    r"^\s*"
    r"(?P<name>\[[^\[\]]+\]|[A-Za-z_][A-Za-z0-9_.]*)"
    r"\s*$",
)

# An expression with trailing `AS [Target]`. Used for function-call
# defs where we can recover the target name but not the source field.
_AS_TARGET_RE = re.compile(
    r"\s+AS\s+"
    r"(?P<tgt>\[[^\[\]]+\]|[A-Za-z_][A-Za-z0-9_.]*)"
    r"\s*$",
    re.IGNORECASE,
)


def parse_field_renames(script: str) -> Dict[str, Dict[str, str]]:
    """Return ``{final_table_name: {engine_field: original_field}}``.

    The map is keyed by the **final** (post-RENAME) table name so
    downstream code can look up renames using the names that
    ``GetTablesAndKeys`` and the PBI tables actually carry.

    For each field within a table:
      * Bracketed simple-rename pattern -> ``{target: source}``.
      * Plain identifier (no rename) -> ``{name: name}`` (identity).
      * Expression with AS target -> ``{target: target}`` (identity:
        the engine field has no recoverable friendlier name).

    Returns ``{}`` if the script is empty or unparseable.
    """
    if not script:
        return {}

    rename_map: Dict[str, str] = {}
    for m in _RENAME_RE.finditer(script):
        src = (m.group("src") or "").strip()
        dst = (m.group("dst") or "").strip()
        if src and dst:
            rename_map[src] = dst
    if rename_map:
        _log.info(f"Parsed {len(rename_map)} RENAME TABLE statement(s).")

    per_table: Dict[str, Dict[str, str]] = {}
    blocks = 0
    for m in _LOAD_BLOCK_RE.finditer(script):
        tname_raw = (m.group("tname") or "").strip()
        if not tname_raw:
            continue
        # Resolve through the rename map to the final table name. A
        # table that was never renamed maps to itself.
        final_name = rename_map.get(tname_raw, tname_raw).strip()
        if not final_name:
            continue
        body = m.group("body") or ""
        renames = per_table.setdefault(final_name, {})
        for tgt, src in _parse_load_body(body).items():
            # Multiple LOAD blocks may contribute to the same final
            # table (CONCATENATE, JOIN). Don't clobber an earlier
            # non-identity mapping with an identity one.
            existing = renames.get(tgt)
            if existing is None:
                renames[tgt] = src
            elif existing == tgt and src != tgt:
                renames[tgt] = src
        blocks += 1

    if per_table:
        _log.info(
            f"Parsed {blocks} LOAD block(s) across "
            f"{len(per_table)} final table(s); "
            f"{sum(len(v) for v in per_table.values())} field def(s) recovered."
        )
    return per_table


# `LIB CONNECT TO [name];` -- names the active data connection. Everything
# loaded via `SQL SELECT` after it draws from that connection until the next
# `LIB CONNECT TO`.
_LIB_CONNECT_RE = re.compile(
    r"LIB\s+CONNECT\s+TO\s+\[?(?P<conn>[^\]\[;\n]+?)\]?\s*;",
    re.IGNORECASE,
)

# A table block sourced from a SQL connection:
#   [tname]:
#   <optional LOAD ...;>
#   SQL SELECT <cols> FROM <src>;
# The optional LOAD is the Qlik transform layer; the SQL SELECT is the pushdown
# to the connection. `src` is `catalog.schema.table` (back-ticked, bracketed, or
# bare). Non-greedy so each block matches its own FROM.
_SQL_TABLE_RE = re.compile(
    r"(?:^|;|\n)\s*"
    r"\[?(?P<tname>[A-Za-z_][^\]\[\n;:]{0,200}?)\]?"
    r"\s*:\s*"
    # Optional Qlik transform LOAD. A LOAD statement has no internal ';',
    # so [^;] keeps this from swallowing across statement/table boundaries
    # (which would mis-attribute the table name).
    r"(?:LOAD\b[^;]*?;\s*)?"
    r"SQL\s+SELECT\b(?P<cols>[^;]*?)\bFROM\b\s+(?P<src>[^;]+?)\s*;",
    re.IGNORECASE,
)

# A back-ticked / bracketed / quoted identifier in a SQL column list.
_SQL_COL_RE = re.compile(r"`([^`]+)`|\"([^\"]+)\"|\[([^\]]+)\]|([A-Za-z_][A-Za-z0-9_]*)")


def _strip_sql_ident(tok: str) -> str:
    """Strip back-ticks / brackets / double-quotes from one SQL identifier."""
    t = (tok or "").strip()
    for op, cl in (("`", "`"), ("[", "]"), ('"', '"')):
        if len(t) >= 2 and t.startswith(op) and t.endswith(cl):
            return t[1:-1].strip()
    return t


def _split_dotted_source(src: str):
    """Split a SQL FROM source ``catalog.schema.table`` (any quoting) into
    ``(catalog, schema, table)``. Missing leading parts come back ``""``."""
    src = (src or "").strip()
    # Split on dots that are NOT inside back-ticks / brackets / quotes.
    parts: List[str] = []
    buf: List[str] = []
    quote = ""
    for c in src:
        if quote:
            buf.append(c)
            if (quote == "`" and c == "`") or (quote == "[" and c == "]") or (quote == '"' and c == '"'):
                quote = ""
        elif c in "`[\"":
            quote = c
            buf.append(c)
        elif c == ".":
            parts.append("".join(buf)); buf = []
        else:
            buf.append(c)
    if buf:
        parts.append("".join(buf))
    parts = [_strip_sql_ident(p) for p in parts if p.strip()]
    if not parts:
        return "", "", ""
    table = parts[-1]
    schema = parts[-2] if len(parts) >= 2 else ""
    catalog = parts[-3] if len(parts) >= 3 else ""
    return catalog, schema, table


def parse_db_sources(script: str) -> Dict[str, Dict[str, object]]:
    """Detect tables loaded from a SQL data connection (``LIB CONNECT TO`` +
    ``SQL SELECT ... FROM catalog.schema.table``).

    Returns ``{final_table_name: {connection, catalog, schema, source_table,
    sql_columns}}`` -- everything needed to repoint that table at its live
    source instead of the engine-loaded snapshot. ``sql_columns`` is the raw
    column list the SQL returns (so the caller can tell which model columns the
    source can actually deliver vs. Qlik-computed ones). Table names are
    resolved through ``RENAME TABLE`` to the final (post-script) name so they
    line up with the engine schema and the PBI tables. ``{}`` when the script
    has no SQL-connection tables (the pure file/QVD case)."""
    if not script:
        return {}

    # RENAME TABLE map (same resolution parse_field_renames uses).
    rename_map: Dict[str, str] = {}
    for m in _RENAME_RE.finditer(script):
        s = (m.group("src") or "").strip()
        d = (m.group("dst") or "").strip()
        if s and d:
            rename_map[s] = d

    # Offsets of each LIB CONNECT TO, to attribute the active connection.
    connects = [(m.start(), (m.group("conn") or "").strip())
                for m in _LIB_CONNECT_RE.finditer(script)]

    def _active_conn(pos: int) -> str:
        name = ""
        for off, conn in connects:
            if off < pos:
                name = conn
            else:
                break
        return name

    out: Dict[str, Dict[str, object]] = {}
    for m in _SQL_TABLE_RE.finditer(script):
        tname_raw = (m.group("tname") or "").strip()
        if not tname_raw or tname_raw.upper() in ("LOAD", "SQL", "SELECT"):
            continue
        final = rename_map.get(tname_raw, tname_raw).strip()
        if not final:
            continue
        catalog, schema, table = _split_dotted_source(m.group("src") or "")
        if not table:
            continue
        cols: List[str] = []
        for cm in _SQL_COL_RE.finditer(m.group("cols") or ""):
            tok = next((g for g in cm.groups() if g), "")
            tok = tok.strip()
            # Skip SQL keywords that can appear in a column list.
            if tok and tok.upper() not in ("DISTINCT", "AS", "ALL"):
                cols.append(tok)
        out[final] = {
            "connection":   _active_conn(m.start()),
            "catalog":      catalog,
            "schema":       schema,
            "source_table": table,
            "sql_columns":  cols,
        }

    if out:
        _log.info(
            f"Parsed {len(out)} SQL-connection table(s) from the load script "
            f"(connections: {sorted({str(v['connection']) for v in out.values()})})."
        )
    return out


def _parse_load_body(body: str) -> Dict[str, str]:
    """Return ``{engine_field: original_field}`` for one LOAD body."""
    out: Dict[str, str] = {}
    for part in _split_field_defs(body):
        part = part.strip()
        if not part:
            continue
        # Strip comments and trailing semicolons.
        part = re.sub(r"//[^\n]*", "", part).strip().rstrip(";").strip()
        if not part:
            continue

        m = _SIMPLE_RENAME_RE.match(part)
        if m:
            src = _strip_brackets(m.group("src"))
            tgt = _strip_brackets(m.group("tgt"))
            if src and tgt:
                out[tgt] = src
            continue

        m = _PLAIN_FIELD_RE.match(part)
        if m:
            name = _strip_brackets(m.group("name"))
            if name:
                out.setdefault(name, name)
            continue

        # Expression with trailing AS target (function calls). The
        # engine field is the target; no friendlier source name is
        # recoverable. Map it to itself.
        m = _AS_TARGET_RE.search(part)
        if m:
            tgt = _strip_brackets(m.group("tgt"))
            if tgt:
                out.setdefault(tgt, tgt)
    return out


def _split_field_defs(body: str) -> List[str]:
    """Comma-split a LOAD body, respecting nested brackets and parens.

    A naive ``body.split(",")`` would break function calls
    (``GeoMakePoint([Lat], [Long]) AS [Foo]``) into pieces. We track
    nesting depth and only split at commas at depth zero.
    """
    parts: List[str] = []
    buf: List[str] = []
    depth_paren = 0
    depth_bracket = 0
    for c in body:
        if c == "(":
            depth_paren += 1
            buf.append(c)
        elif c == ")":
            depth_paren = max(0, depth_paren - 1)
            buf.append(c)
        elif c == "[":
            depth_bracket += 1
            buf.append(c)
        elif c == "]":
            depth_bracket = max(0, depth_bracket - 1)
            buf.append(c)
        elif c == "," and depth_paren == 0 and depth_bracket == 0:
            parts.append("".join(buf))
            buf = []
        else:
            buf.append(c)
    if buf:
        parts.append("".join(buf))
    return parts


def _strip_brackets(name: str) -> str:
    n = (name or "").strip()
    if len(n) >= 2 and n.startswith("[") and n.endswith("]"):
        return n[1:-1]
    return n
