table 'Dim_HCO (2)'
	lineageTag: 39c4c647-a788-9cd4-c2a0-301dd5dbd47c

	column City
		dataType: string
		lineageTag: 7ffd73e6-6960-ddcd-de7e-0ac0b8d14aae
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'HCO ID'
		dataType: int64
		lineageTag: f4fb1ce9-8e59-4f29-2485-1142cab538f1
		summarizeBy: none
		sourceColumn: HCO_ID

		annotation SummarizationSetBy = Automatic

	column 'HCO Name'
		dataType: string
		lineageTag: a8a24b5b-939a-df11-9381-17c611636ffa
		summarizeBy: none
		sourceColumn: HCO_Name

		annotation SummarizationSetBy = Automatic

	column 'HCO Type'
		dataType: string
		lineageTag: 8f16ee84-5e47-d37b-68ec-d625a29d625a
		summarizeBy: none
		sourceColumn: HCO_Type

		annotation SummarizationSetBy = Automatic

	column 'Incoming Referrals'
		dataType: int64
		lineageTag: 8ae35da7-163d-21d3-dcaa-46bf21f99343
		summarizeBy: sum
		sourceColumn: Incoming_Referrals

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 1fed6606-a72b-293d-84b7-8362369d80df
		summarizeBy: none
		sourceColumn: Latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		lineageTag: 81cf456e-8ea7-56ee-0d74-88df487339d1
		summarizeBy: none
		sourceColumn: Longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column 'Mistreated Patients'
		dataType: int64
		lineageTag: 55600d32-0886-db7b-7598-03990c435cb5
		summarizeBy: sum
		sourceColumn: Mistreated_Patients

		annotation SummarizationSetBy = Automatic

	column 'Outgoing Referrals'
		dataType: int64
		lineageTag: 22eb145a-f9e0-7b12-e2f9-acd8f3487ff4
		summarizeBy: sum
		sourceColumn: Outgoing_Referrals

		annotation SummarizationSetBy = Automatic

	column 'Patients Count'
		dataType: int64
		lineageTag: 3e89e477-54db-f03a-8555-d87046333cfa
		summarizeBy: sum
		sourceColumn: Patients_Count

		annotation SummarizationSetBy = Automatic

	column 'Patients Diagnosed'
		dataType: int64
		lineageTag: fa53de9a-e6f3-28f1-c053-b24d745af651
		summarizeBy: sum
		sourceColumn: Patients_Diagnosed

		annotation SummarizationSetBy = Automatic

	column 'Patients Prescribed'
		dataType: int64
		lineageTag: 3d692024-5d91-b625-a13b-bc61f231193f
		summarizeBy: sum
		sourceColumn: Patients_Prescribed

		annotation SummarizationSetBy = Automatic

	column 'Patients Treated'
		dataType: int64
		lineageTag: 2a72bde7-8a45-fb35-23fa-6da7e5caa2f5
		summarizeBy: sum
		sourceColumn: Patients_Treated

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 788b0569-5a0d-12ee-393a-5a5b02c9faca
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Territory Name'
		dataType: string
		lineageTag: aa71c15a-ff03-bc34-4c9a-e39a30896eec
		summarizeBy: none
		sourceColumn: Territory_Name

		annotation SummarizationSetBy = Automatic

	column 'Total HCPs'
		dataType: int64
		lineageTag: 246fb6b9-9c27-2118-c1bc-1cc12633351d
		summarizeBy: sum
		sourceColumn: Total_HCPs

		annotation SummarizationSetBy = Automatic

	column ZIP
		dataType: int64
		lineageTag: c4142c22-5e9a-3d3d-06b0-ac53540e653b
		summarizeBy: none
		sourceColumn: ZIP

		annotation SummarizationSetBy = Automatic

	partition 'Dim_HCO (2)' = m
		mode: import
		source =
			let
			    Source = Table.FromRows({}, type table [#"City" = text, #"HCO_ID" = number, #"HCO_Name" = text, #"HCO_Type" = text, #"Incoming_Referrals" = number, #"Latitude" = number, #"Longitude" = number, #"Mistreated_Patients" = number, #"Outgoing_Referrals" = number, #"Patients_Count" = number, #"Patients_Diagnosed" = number, #"Patients_Prescribed" = number, #"Patients_Treated" = number, #"State" = text, #"Territory_Name" = text, #"Total_HCPs" = number, #"ZIP" = number])
			in
			    Source

	annotation PBI_ResultType = Table
