table dim_hco
	lineageTag: a3324092-dd44-fe49-058e-d21b404a760b

	column 'City (dim hco)'
		dataType: string
		lineageTag: c9a01b70-1864-6d6b-71c1-f4fc6b1bd06e
		summarizeBy: none
		sourceColumn: City (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'Email (dim hco)'
		dataType: string
		lineageTag: 7474b086-dec6-51fc-73b1-ac039573b964
		summarizeBy: none
		sourceColumn: Email (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'HCO ID (dim hco)'
		dataType: int64
		lineageTag: 7a10dd52-5403-f82e-a029-f268e30e931b
		summarizeBy: none
		sourceColumn: HCO_ID (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'HCO Name'
		dataType: string
		lineageTag: 6959d2ff-5690-f84d-a3b9-58d277532d2f
		summarizeBy: none
		sourceColumn: HCO_Name

		annotation SummarizationSetBy = Automatic

	column 'HCO Type'
		dataType: string
		lineageTag: 28208620-266c-52ff-c663-2f9385b93f10
		summarizeBy: none
		sourceColumn: HCO_Type

		annotation SummarizationSetBy = Automatic

	column 'Incoming Referrals (dim hco)'
		dataType: int64
		lineageTag: a715fa49-0a2d-95fa-7274-f737cec67f24
		summarizeBy: sum
		sourceColumn: Incoming_Referrals (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'Latitude (dim hco)'
		dataType: double
		lineageTag: c7ec04be-c919-4c99-de6b-6fd36d11d1cc
		summarizeBy: none
		sourceColumn: Latitude (dim_hco)
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column 'Longitude (dim hco)'
		dataType: double
		lineageTag: 578b9c23-8714-0134-62b9-ec79c706824b
		summarizeBy: none
		sourceColumn: Longitude (dim_hco)
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column 'Mistreated Patients (dim hco)'
		dataType: int64
		lineageTag: 64e70d11-bae5-62a9-6319-16bebc8e7893
		summarizeBy: sum
		sourceColumn: Mistreated_Patients (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'Outgoing Referrals (dim hco)'
		dataType: int64
		lineageTag: 6476e4fc-fb81-7b2d-9b23-df1da1871677
		summarizeBy: sum
		sourceColumn: Outgoing_Referrals (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'Patients Count (dim hco)'
		dataType: int64
		lineageTag: 21f011f9-ed6e-e553-5194-c24bf2e87d29
		summarizeBy: sum
		sourceColumn: Patients_Count (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'Patients Diagnosed (dim hco)'
		dataType: int64
		lineageTag: 4f43cd47-ba49-70f6-0ebe-c777d932fb85
		summarizeBy: sum
		sourceColumn: Patients_Diagnosed (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'Patients Prescribed (dim hco)'
		dataType: int64
		lineageTag: b6b5b186-9441-a9fa-77c4-13314d00ccc1
		summarizeBy: sum
		sourceColumn: Patients_Prescribed (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'Patients Treated (dim hco)'
		dataType: int64
		lineageTag: 54350579-de9e-a3c1-7b9e-e5feda1f5d17
		summarizeBy: sum
		sourceColumn: Patients_Treated (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'Region (dim hco)'
		dataType: string
		lineageTag: 5e64ffbc-e48b-b53a-4fa5-6bd28d92d88d
		summarizeBy: none
		sourceColumn: Region (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'State (dim hco)'
		dataType: string
		lineageTag: 2995f7b2-6a48-9d6b-0b6e-2d1a68ca7702
		summarizeBy: none
		sourceColumn: State (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'Territory (dim hco)'
		dataType: string
		lineageTag: f9bd6e1e-ae47-90da-819b-104ae15e4b52
		summarizeBy: none
		sourceColumn: Territory (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'Territory Name (dim hco)'
		dataType: string
		lineageTag: 564a7730-8e52-582a-4cf7-4afce65a2623
		summarizeBy: none
		sourceColumn: Territory_Name (dim_hco)

		annotation SummarizationSetBy = Automatic

	column 'Total HCPs'
		dataType: int64
		lineageTag: 19a24a37-f440-b1bd-455f-34d2f1ece221
		summarizeBy: sum
		sourceColumn: Total_HCPs

		annotation SummarizationSetBy = Automatic

	column 'ZIP (dim hco)'
		dataType: int64
		lineageTag: d5030583-fbc6-e452-8e26-ef2a3253e3d5
		summarizeBy: none
		sourceColumn: ZIP (dim_hco)

		annotation SummarizationSetBy = Automatic

	partition dim_hco = m
		mode: import
		source =
			let
			    // TODO: live connection class 'databricks' - rewire the connector in PBI Desktop
			    Source = Table.FromRows({}, type table [#"City (dim_hco)" = text, #"Email (dim_hco)" = text, #"HCO_ID (dim_hco)" = number, #"HCO_Name" = text, #"HCO_Type" = text, #"Incoming_Referrals (dim_hco)" = number, #"Latitude (dim_hco)" = number, #"Longitude (dim_hco)" = number, #"Mistreated_Patients (dim_hco)" = number, #"Outgoing_Referrals (dim_hco)" = number, #"Patients_Count (dim_hco)" = number, #"Patients_Diagnosed (dim_hco)" = number, #"Patients_Prescribed (dim_hco)" = number, #"Patients_Treated (dim_hco)" = number, #"Region (dim_hco)" = text, #"State (dim_hco)" = text, #"Territory (dim_hco)" = text, #"Territory_Name (dim_hco)" = text, #"Total_HCPs" = number, #"ZIP (dim_hco)" = number])
			in
			    Source

	annotation PBI_ResultType = Table
