table Dim_HCP
	lineageTag: 793e7c06-cef2-88e0-cb0b-0a7215dd2947

	column 'Address Line1'
		dataType: string
		lineageTag: cfb4e769-7605-7e21-5a79-ba7f77c7e6ef
		summarizeBy: none
		sourceColumn: Address_Line1

		annotation SummarizationSetBy = Automatic

	column 'Bridge Score'
		dataType: double
		lineageTag: 3ab27a90-4479-6b55-1cb1-74c2a75d8d3c
		summarizeBy: sum
		sourceColumn: Bridge_Score

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 7ffd73e6-6960-ddcd-de7e-0ac0b8d14aae
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Cluster ID'
		dataType: int64
		lineageTag: edf2063b-4ec1-0b1f-f74d-46be694f014f
		summarizeBy: none
		sourceColumn: Cluster_ID

		annotation SummarizationSetBy = Automatic

	column 'Eigenvector Score'
		dataType: double
		lineageTag: cbd699c5-41d7-439d-5a5f-ac1d3ca91439
		summarizeBy: sum
		sourceColumn: Eigenvector_Score

		annotation SummarizationSetBy = Automatic

	column 'Final Segment (group)' = SWITCH(TRUE(), [Final Segment] IN { "Key Influencer" }, "L1", [Final Segment] IN { "Bridger" }, "M1", [Final Segment] IN { "Diagnoser", "Prescriber", "Referrer" }, "N1", [Final Segment] )
		dataType: string
		lineageTag: 8f21c3f6-2a14-b192-498c-2c43f5fa8197
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Final Segment'
		dataType: string
		lineageTag: ad188a8b-bf6a-15a2-a366-2087200bd714
		summarizeBy: none
		sourceColumn: Final_Segment

		annotation SummarizationSetBy = Automatic

	column 'Hco Id'
		dataType: int64
		lineageTag: f4fb1ce9-8e59-4f29-2485-1142cab538f1
		summarizeBy: none
		sourceColumn: HCO_ID

		annotation SummarizationSetBy = Automatic

	column 'Hcp Id'
		dataType: int64
		lineageTag: de05791f-78cc-065e-553f-1fb02c291de9
		summarizeBy: none
		sourceColumn: HCP_ID

		annotation SummarizationSetBy = Automatic

	column 'HCP Name'
		dataType: string
		lineageTag: 8db3c3de-d687-3ccc-a892-3b5a8b81e72a
		summarizeBy: none
		sourceColumn: HCP_Name

		annotation SummarizationSetBy = Automatic

	column 'Incoming Referrals'
		dataType: int64
		lineageTag: 8ae35da7-163d-21d3-dcaa-46bf21f99343
		summarizeBy: sum
		sourceColumn: Incoming_Referrals

		annotation SummarizationSetBy = Automatic

	column 'Influence Score'
		dataType: double
		lineageTag: ad7fc01a-a6ef-9ddc-e77e-bf7d31f1faaa
		summarizeBy: sum
		sourceColumn: Influence_Score

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 1fed6606-a72b-293d-84b7-8362369d80df
		summarizeBy: none
		sourceColumn: Latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		lineageTag: 81cf456e-8ea7-56ee-0d74-88df487339d1
		summarizeBy: none
		sourceColumn: Longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column 'Mistreated Patients'
		dataType: int64
		lineageTag: 55600d32-0886-db7b-7598-03990c435cb5
		summarizeBy: sum
		sourceColumn: Mistreated_Patients

		annotation SummarizationSetBy = Automatic

	column 'Outgoing Referrals'
		dataType: int64
		lineageTag: 22eb145a-f9e0-7b12-e2f9-acd8f3487ff4
		summarizeBy: sum
		sourceColumn: Outgoing_Referrals

		annotation SummarizationSetBy = Automatic

	column 'Patients Count'
		dataType: int64
		lineageTag: 3e89e477-54db-f03a-8555-d87046333cfa
		summarizeBy: sum
		sourceColumn: Patients_Count

		annotation SummarizationSetBy = Automatic

	column 'Patients Diagnosed'
		dataType: int64
		lineageTag: fa53de9a-e6f3-28f1-c053-b24d745af651
		summarizeBy: sum
		sourceColumn: Patients_Diagnosed

		annotation SummarizationSetBy = Automatic

	column 'Patients Prescribed'
		dataType: int64
		lineageTag: 3d692024-5d91-b625-a13b-bc61f231193f
		summarizeBy: sum
		sourceColumn: Patients_Prescribed

		annotation SummarizationSetBy = Automatic

	column 'Patients Treated'
		dataType: int64
		lineageTag: 2a72bde7-8a45-fb35-23fa-6da7e5caa2f5
		summarizeBy: sum
		sourceColumn: Patients_Treated

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 657fc061-d41d-4a4d-e498-b3be38704380
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Specialty (group)' = SWITCH(TRUE(), [Specialty] IN { "NP/PA", "Other Non-Specialists", "Other Specialists" }, "Others", [Specialty] IN { "Psychiatrist", "Psychologist" }, "Psychiatrist", [Specialty] )
		dataType: string
		lineageTag: 8fc02117-20c7-2fb4-e8fd-ffae466bdf72
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Specialty
		dataType: string
		lineageTag: 23d28969-f00f-9794-57d8-89404100ad7e
		summarizeBy: none
		sourceColumn: Specialty

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 788b0569-5a0d-12ee-393a-5a5b02c9faca
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Territory Name'
		dataType: string
		lineageTag: aa71c15a-ff03-bc34-4c9a-e39a30896eec
		summarizeBy: none
		sourceColumn: Territory_Name

		annotation SummarizationSetBy = Automatic

	column ZIP
		dataType: int64
		lineageTag: c4142c22-5e9a-3d3d-06b0-ac53540e653b
		summarizeBy: none
		sourceColumn: ZIP

		annotation SummarizationSetBy = Automatic

	column Affiliation
		dataType: string
		lineageTag: 1e835a64-820e-6f2b-f537-81927b7ff3d9
		summarizeBy: none
		sourceColumn: Affiliation

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 53e1a5df-1b11-d654-e5f1-d0f4068df0f1
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: int64
		lineageTag: 43ff41b9-c024-3ff0-b9f2-0fc1965e819b
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	measure 'Sum of Patients' = SUM('Dim_HCO'[Patients Count])
		lineageTag: dbbd4a06-cfa4-122b-890b-4a7406d39859

		annotation SummarizationSetBy = Automatic

	measure 'Total Territories' = DISTINCTCOUNT('Dim_HCP'[Territory])
		lineageTag: 221844d1-b794-b749-dac5-b363b825bb9f

		annotation SummarizationSetBy = Automatic

	partition Dim_HCP = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(RepoPath & "/data/federated.1rbitm00scg_8a2dec53/Extract.Dim!HCP_1F6647AACEA24AE_4ed5b4dc.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"HCP_ID", Int64.Type}, {"HCP_Name", type text}, {"Address_Line1", type text}, {"City", type text}, {"State", type text}, {"ZIP", Int64.Type}, {"Specialty", type text}, {"Influence_Score", type number}, {"Bridge_Score", type number}, {"Eigenvector_Score", type number}, {"Final_Segment", type text}, {"Patients_Treated", Int64.Type}, {"Patients_Prescribed", Int64.Type}, {"Patients_Diagnosed", Int64.Type}, {"Patients_Count", Int64.Type}, {"Mistreated_Patients", Int64.Type}, {"Affiliation", type text}, {"HCO_ID", Int64.Type}, {"Email", type text}, {"Region", type text}, {"Territory", Int64.Type}, {"Territory_Name", type text}, {"Latitude", type number}, {"Longitude", type number}, {"Cluster_ID", Int64.Type}, {"Incoming_Referrals", Int64.Type}, {"Outgoing_Referrals", Int64.Type}})
			in
			    ChangedTypes

	annotation PBI_ResultType = Table
