table Fact_Referral_Edge
	lineageTag: c80db2d2-eda0-135a-f122-f70e15c10b61

	column 'From Cluster ID'
		dataType: int64
		lineageTag: 2097fa94-a0ef-68ff-a026-12471f064f91
		summarizeBy: none
		sourceColumn: From_Cluster_ID

		annotation SummarizationSetBy = Automatic

	column 'From HCO ID'
		dataType: int64
		lineageTag: c3438d37-512b-0beb-da50-1d568aa3eced
		summarizeBy: none
		sourceColumn: From_HCO_ID

		annotation SummarizationSetBy = Automatic

	column 'From HCP ID'
		dataType: int64
		lineageTag: 2025706c-40b1-fa44-e47b-5a7d99cb1063
		summarizeBy: none
		sourceColumn: From_HCP_ID

		annotation SummarizationSetBy = Automatic

	column 'From HCP Name'
		dataType: string
		lineageTag: 29345588-a0b8-6803-940b-4b9da96dbfb1
		summarizeBy: none
		sourceColumn: From_HCP_Name

		annotation SummarizationSetBy = Automatic

	column 'From Latitude'
		dataType: double
		lineageTag: 5c550e45-6cc1-d73e-1326-57e36b8264bb
		summarizeBy: none
		sourceColumn: From_Latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column 'From Longitude'
		dataType: double
		lineageTag: 5534ab59-c0bb-a8db-9989-d34da5f396e2
		summarizeBy: none
		sourceColumn: From_Longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column 'From Region'
		dataType: string
		lineageTag: 5bc6675b-9843-db09-6c7e-f4d2aca48d01
		summarizeBy: none
		sourceColumn: From_Region

		annotation SummarizationSetBy = Automatic

	column 'From Territory'
		dataType: int64
		lineageTag: 3c0af0ac-3c1f-2780-f108-3d99d5e9e0b2
		summarizeBy: sum
		sourceColumn: From_Territory

		annotation SummarizationSetBy = Automatic

	column 'From Territory Name'
		dataType: string
		lineageTag: e70d87ad-594a-13be-03c3-6f0cb50a328a
		summarizeBy: none
		sourceColumn: From_Territory_Name

		annotation SummarizationSetBy = Automatic

	column 'Link ID'
		dataType: int64
		lineageTag: 17730417-5f7d-3421-7620-3f3af9ed594d
		summarizeBy: none
		sourceColumn: Link_ID

		annotation SummarizationSetBy = Automatic

	column 'To Cluster ID'
		dataType: int64
		lineageTag: 66ac1b28-4b1f-6826-03cf-32ee34975c5a
		summarizeBy: none
		sourceColumn: To_Cluster_ID

		annotation SummarizationSetBy = Automatic

	column 'To HCO ID'
		dataType: int64
		lineageTag: b5d5ece0-0d35-1135-5eda-062bf29dd3b3
		summarizeBy: none
		sourceColumn: To_HCO_ID

		annotation SummarizationSetBy = Automatic

	column 'To HCP ID'
		dataType: int64
		lineageTag: cb689ca9-e45f-2106-7e1b-a6e951c4988b
		summarizeBy: none
		sourceColumn: To_HCP_ID

		annotation SummarizationSetBy = Automatic

	column 'To HCP Name'
		dataType: string
		lineageTag: 767b499b-ac0a-f573-742e-87dab873b674
		summarizeBy: none
		sourceColumn: To_HCP_Name

		annotation SummarizationSetBy = Automatic

	column 'To Latitude'
		dataType: double
		lineageTag: c4c14a3a-80a2-e0ef-2839-84b0d3628c16
		summarizeBy: none
		sourceColumn: To_Latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column 'To Longitude'
		dataType: double
		lineageTag: b25133fe-d0d9-2ffe-cf64-925e232c3fcb
		summarizeBy: none
		sourceColumn: To_Longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column 'To Region'
		dataType: string
		lineageTag: 56746b04-abc1-6ecb-3e1c-2506e0e7af04
		summarizeBy: none
		sourceColumn: To_Region

		annotation SummarizationSetBy = Automatic

	column 'To Territory'
		dataType: int64
		lineageTag: 38a37649-6d7d-749a-52d2-c023cc0bd4e1
		summarizeBy: sum
		sourceColumn: To_Territory

		annotation SummarizationSetBy = Automatic

	column 'To Territory Name'
		dataType: string
		lineageTag: 71eab6ba-7ba0-d5a0-e53b-d8f89414c1d8
		summarizeBy: none
		sourceColumn: To_Territory_Name

		annotation SummarizationSetBy = Automatic

	column 'from HCO name'
		dataType: string
		lineageTag: 86fe2b8a-2ad8-f682-e15c-871873a4222f
		summarizeBy: none
		sourceColumn: from_HCO_name

		annotation SummarizationSetBy = Automatic

	column 'to HCO name'
		dataType: string
		lineageTag: 47cf9a1f-b692-8e0e-38e7-efd6fbed94a5
		summarizeBy: none
		sourceColumn: to_HCO_name

		annotation SummarizationSetBy = Automatic

	partition Fact_Referral_Edge = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(RepoPath & "/data/federated.1rbitm00scg_8a2dec53/Extract.Fact!Referral!Edge_C7B5_98aaef68.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"Link_ID", Int64.Type}, {"From_HCP_ID", Int64.Type}, {"To_HCP_ID", Int64.Type}, {"From_HCO_ID", Int64.Type}, {"To_HCO_ID", Int64.Type}, {"From_HCP_Name", type text}, {"To_HCP_Name", type text}, {"from_HCO_name", type text}, {"to_HCO_name", type text}, {"From_Latitude", type number}, {"From_Longitude", type number}, {"To_Latitude", type number}, {"To_Longitude", type number}, {"From_Region", type text}, {"From_Territory", Int64.Type}, {"From_Territory_Name", type text}, {"From_Cluster_ID", Int64.Type}, {"To_Region", type text}, {"To_Territory", Int64.Type}, {"To_Territory_Name", type text}, {"To_Cluster_ID", Int64.Type}})
			in
			    ChangedTypes

	annotation PBI_ResultType = Table
