table 'Dim_HCO (2)'
	lineageTag: ba2a6102-e7b9-9885-6f66-12930ae9b1c0

	column City
		dataType: string
		lineageTag: 86a6c489-45b5-8bf5-6a74-4d66249347a1
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'HCO ID'
		dataType: int64
		lineageTag: 8532e16a-78c0-6582-5da3-e30551e353e7
		summarizeBy: none
		sourceColumn: HCO_ID

		annotation SummarizationSetBy = Automatic

	column 'HCO Name'
		dataType: string
		lineageTag: 0951c18b-77a3-052d-2d1a-599130154f67
		summarizeBy: none
		sourceColumn: HCO_Name

		annotation SummarizationSetBy = Automatic

	column 'HCO Type'
		dataType: string
		lineageTag: 4802da5c-ad9c-f710-496f-8b8c6f689de6
		summarizeBy: none
		sourceColumn: HCO_Type

		annotation SummarizationSetBy = Automatic

	column 'Incoming Referrals'
		dataType: int64
		lineageTag: 32e8bdae-366a-b2bb-77ca-607d7d75a51a
		summarizeBy: sum
		sourceColumn: Incoming_Referrals

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 73de68fd-1675-0474-13d3-52129ef850fc
		summarizeBy: none
		sourceColumn: Latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		lineageTag: 9dcdac30-908e-ad82-be0e-322b250e4561
		summarizeBy: none
		sourceColumn: Longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column 'Mistreated Patients'
		dataType: int64
		lineageTag: ee951f9f-cba6-2a61-5429-ee7c8f23a18d
		summarizeBy: sum
		sourceColumn: Mistreated_Patients

		annotation SummarizationSetBy = Automatic

	column 'Outgoing Referrals'
		dataType: int64
		lineageTag: 0a7d363d-89e1-fb1f-87ba-3dd5e85d3704
		summarizeBy: sum
		sourceColumn: Outgoing_Referrals

		annotation SummarizationSetBy = Automatic

	column 'Patients Count'
		dataType: int64
		lineageTag: f3551535-5cdb-dd67-7d09-8cdd4f354142
		summarizeBy: sum
		sourceColumn: Patients_Count

		annotation SummarizationSetBy = Automatic

	column 'Patients Diagnosed'
		dataType: int64
		lineageTag: 951f4b61-5462-fd72-c976-0ef4c787da28
		summarizeBy: sum
		sourceColumn: Patients_Diagnosed

		annotation SummarizationSetBy = Automatic

	column 'Patients Prescribed'
		dataType: int64
		lineageTag: 231f0882-afdd-2541-b2b9-4f63531a86cb
		summarizeBy: sum
		sourceColumn: Patients_Prescribed

		annotation SummarizationSetBy = Automatic

	column 'Patients Treated'
		dataType: int64
		lineageTag: 745ec6f3-e410-fedd-3b6b-7a5f6760cf71
		summarizeBy: sum
		sourceColumn: Patients_Treated

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: a9f556f0-cc18-4fe5-cb6a-759a2537299a
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Territory Name'
		dataType: string
		lineageTag: 6c360f24-a6a9-9b80-4441-a265b9d8bd61
		summarizeBy: none
		sourceColumn: Territory_Name

		annotation SummarizationSetBy = Automatic

	column 'Total HCPs'
		dataType: int64
		lineageTag: 7fc21cfe-850e-fdb0-422b-e483a49645d7
		summarizeBy: sum
		sourceColumn: Total_HCPs

		annotation SummarizationSetBy = Automatic

	column ZIP
		dataType: int64
		lineageTag: 724bc984-40ad-1a83-3f38-0a0a7a9c3171
		summarizeBy: none
		sourceColumn: ZIP

		annotation SummarizationSetBy = Automatic

	partition 'Dim_HCO (2)' = m
		mode: import
		source =
			let
			    Source = Table.FromRows({}, type table [#"City" = text, #"HCO_ID" = number, #"HCO_Name" = text, #"HCO_Type" = text, #"Incoming_Referrals" = number, #"Latitude" = number, #"Longitude" = number, #"Mistreated_Patients" = number, #"Outgoing_Referrals" = number, #"Patients_Count" = number, #"Patients_Diagnosed" = number, #"Patients_Prescribed" = number, #"Patients_Treated" = number, #"State" = text, #"Territory_Name" = text, #"Total_HCPs" = number, #"ZIP" = number])
			in
			    Source

	annotation PBI_ResultType = Table
