table 'Fact_Referral_Edge (2)'
	lineageTag: 82846fc5-eaf2-fc88-0b30-682008755901

	column 'From Cluster ID'
		dataType: int64
		lineageTag: bd5809c6-34c4-f725-eea4-d3bfd86f58df
		summarizeBy: none
		sourceColumn: From_Cluster_ID

		annotation SummarizationSetBy = Automatic

	column 'From HCO ID'
		dataType: int64
		lineageTag: 203e79fc-4841-2fef-646f-4c8975bd3502
		summarizeBy: none
		sourceColumn: From_HCO_ID

		annotation SummarizationSetBy = Automatic

	column 'From HCP ID'
		dataType: int64
		lineageTag: 13fb165b-dc7c-b74c-28ef-3e26ebbab770
		summarizeBy: none
		sourceColumn: From_HCP_ID

		annotation SummarizationSetBy = Automatic

	column 'From HCP Name'
		dataType: string
		lineageTag: d5a38c83-688b-8186-b1a5-58a8795e3cfc
		summarizeBy: none
		sourceColumn: From_HCP_Name

		annotation SummarizationSetBy = Automatic

	column 'From Latitude'
		dataType: double
		lineageTag: 885cce5b-5c01-86f6-e5b1-8899971e7a30
		summarizeBy: none
		sourceColumn: From_Latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column 'From Longitude'
		dataType: double
		lineageTag: 2db73713-c963-ea72-929c-4dbabd656af4
		summarizeBy: none
		sourceColumn: From_Longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column 'From Region'
		dataType: string
		lineageTag: 62cf5399-883f-b372-9d99-4128b0c06bd2
		summarizeBy: none
		sourceColumn: From_Region

		annotation SummarizationSetBy = Automatic

	column 'From Territory'
		dataType: int64
		lineageTag: 56a8a106-8110-9ec0-2133-3151be66d1b6
		summarizeBy: sum
		sourceColumn: From_Territory

		annotation SummarizationSetBy = Automatic

	column 'From Territory Name'
		dataType: string
		lineageTag: ad15b788-84e7-4cae-910a-f316b4d85874
		summarizeBy: none
		sourceColumn: From_Territory_Name

		annotation SummarizationSetBy = Automatic

	column 'Link ID'
		dataType: int64
		lineageTag: f593709d-96be-5d74-91b0-2b488250bfd2
		summarizeBy: none
		sourceColumn: Link_ID

		annotation SummarizationSetBy = Automatic

	column 'To Cluster ID'
		dataType: int64
		lineageTag: f380fe13-8ae1-e544-cdc5-61cd2668bef4
		summarizeBy: none
		sourceColumn: To_Cluster_ID

		annotation SummarizationSetBy = Automatic

	column 'To HCO ID'
		dataType: int64
		lineageTag: 51dcd3b9-3715-f481-42e9-4bbe85e941f6
		summarizeBy: none
		sourceColumn: To_HCO_ID

		annotation SummarizationSetBy = Automatic

	column 'To HCP ID'
		dataType: int64
		lineageTag: 6b0df989-189b-9f90-1ec1-975390767189
		summarizeBy: none
		sourceColumn: To_HCP_ID

		annotation SummarizationSetBy = Automatic

	column 'To HCP Name'
		dataType: string
		lineageTag: 6ee4485d-c750-03b6-6336-4d2d6c1ce44c
		summarizeBy: none
		sourceColumn: To_HCP_Name

		annotation SummarizationSetBy = Automatic

	column 'To Latitude'
		dataType: double
		lineageTag: 54b421a6-2ac6-634e-5eda-a8eb8bfa32a6
		summarizeBy: none
		sourceColumn: To_Latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column 'To Longitude'
		dataType: double
		lineageTag: faf19c0a-f25e-fd0c-0d1e-c9641abe9125
		summarizeBy: none
		sourceColumn: To_Longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column 'To Region'
		dataType: string
		lineageTag: 42717400-03a4-2257-611c-370b15db2f36
		summarizeBy: none
		sourceColumn: To_Region

		annotation SummarizationSetBy = Automatic

	column 'To Territory'
		dataType: int64
		lineageTag: c8a88acc-e1e6-7062-40e4-1471988b40bd
		summarizeBy: sum
		sourceColumn: To_Territory

		annotation SummarizationSetBy = Automatic

	column 'To Territory Name'
		dataType: string
		lineageTag: 484172f0-a532-011f-e777-6669240dfaea
		summarizeBy: none
		sourceColumn: To_Territory_Name

		annotation SummarizationSetBy = Automatic

	column 'from HCO name'
		dataType: string
		lineageTag: fce3e51d-4f51-d2b7-1cbf-f7124c1a68e5
		summarizeBy: none
		sourceColumn: from_HCO_name

		annotation SummarizationSetBy = Automatic

	column 'to HCO name'
		dataType: string
		lineageTag: a82ebef3-b26d-b862-8223-45bf7d52b136
		summarizeBy: none
		sourceColumn: to_HCO_name

		annotation SummarizationSetBy = Automatic

	partition 'Fact_Referral_Edge (2)' = m
		mode: import
		source =
			let
			    Source = Table.FromRows({}, type table [#"From_Cluster_ID" = number, #"From_HCO_ID" = number, #"From_HCP_ID" = number, #"From_HCP_Name" = text, #"From_Latitude" = number, #"From_Longitude" = number, #"From_Region" = text, #"From_Territory" = number, #"From_Territory_Name" = text, #"Link_ID" = number, #"To_Cluster_ID" = number, #"To_HCO_ID" = number, #"To_HCP_ID" = number, #"To_HCP_Name" = text, #"To_Latitude" = number, #"To_Longitude" = number, #"To_Region" = text, #"To_Territory" = number, #"To_Territory_Name" = text, #"from_HCO_name" = text, #"to_HCO_name" = text])
			in
			    Source

	annotation PBI_ResultType = Table
