table Dim_HCO
	lineageTag: 80fd7afd-5eea-e567-e353-8b8eefad0108

	column City
		dataType: string
		lineageTag: e3775fc5-7329-a4d5-be18-1c064b676682
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'HCO Type (group)' = SWITCH(TRUE(), [HCO Type] IN { "Clinic", "Hospital", "Medical Group" }, "G1", [HCO Type] IN { "Health System", "Provider Organization" }, "G2", [HCO Type] )
		dataType: string
		lineageTag: 9e996726-4fc6-1202-ddc9-b97f811946cd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'HCO ID'
		dataType: int64
		lineageTag: c0ab1ff7-ff19-96d0-25ab-f0ed3570b7ad
		summarizeBy: none
		sourceColumn: HCO_ID

		annotation SummarizationSetBy = Automatic

	column 'HCO Name'
		dataType: string
		lineageTag: d106bfd6-c410-0503-c32d-a6cadc5dcad9
		summarizeBy: none
		sourceColumn: HCO_Name

		annotation SummarizationSetBy = Automatic

	column 'HCO Type'
		dataType: string
		lineageTag: 09715d59-fa62-3e84-89ab-34c3f1ed4e2f
		summarizeBy: none
		sourceColumn: HCO_Type

		annotation SummarizationSetBy = Automatic

	column 'Incoming Referrals'
		dataType: int64
		lineageTag: ca78cf0b-234b-53e2-e077-68da5877c71a
		summarizeBy: sum
		sourceColumn: Incoming_Referrals

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: c733ff31-020f-1742-527a-807566e1ac83
		summarizeBy: none
		sourceColumn: Latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		lineageTag: dd7b796f-1e7e-1297-19f5-0c15cebc6f1c
		summarizeBy: none
		sourceColumn: Longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column 'Mistreated Patients'
		dataType: int64
		lineageTag: 27ce478f-7b28-98ed-a29e-ef5eb6808ff7
		summarizeBy: sum
		sourceColumn: Mistreated_Patients

		annotation SummarizationSetBy = Automatic

	column 'Outgoing Referrals'
		dataType: int64
		lineageTag: 5ea3b7d3-8cb7-46c8-02d5-7ccd74d7cc7a
		summarizeBy: sum
		sourceColumn: Outgoing_Referrals

		annotation SummarizationSetBy = Automatic

	column 'Patients Count'
		dataType: int64
		lineageTag: d0b57cce-b442-5bdc-cc06-794656598e30
		summarizeBy: sum
		sourceColumn: Patients_Count

		annotation SummarizationSetBy = Automatic

	column 'Patients Diagnosed'
		dataType: int64
		lineageTag: 83b1d075-04b9-5f75-bb66-3c33ff412ece
		summarizeBy: sum
		sourceColumn: Patients_Diagnosed

		annotation SummarizationSetBy = Automatic

	column 'Patients Prescribed'
		dataType: int64
		lineageTag: 5a29d15f-2c2d-ed81-7727-7e78cca52196
		summarizeBy: sum
		sourceColumn: Patients_Prescribed

		annotation SummarizationSetBy = Automatic

	column 'Patients Treated'
		dataType: int64
		lineageTag: 6c895621-54c3-7fe7-9605-8e26412bb5d5
		summarizeBy: sum
		sourceColumn: Patients_Treated

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 951402e8-5aba-62d0-3fba-08a57c7341f1
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Territory Name'
		dataType: string
		lineageTag: 8bd28172-4fe7-9b37-7255-1af96df0a3ab
		summarizeBy: none
		sourceColumn: Territory_Name

		annotation SummarizationSetBy = Automatic

	column 'Total HCPs'
		dataType: int64
		lineageTag: 3ae0ae19-5b66-fa08-f745-40a03217d6b9
		summarizeBy: sum
		sourceColumn: Total_HCPs

		annotation SummarizationSetBy = Automatic

	column ZIP
		dataType: int64
		lineageTag: defe08b2-2552-f284-e444-b516de131408
		summarizeBy: none
		sourceColumn: ZIP

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 6b0bc97d-91b5-6b4b-35d1-a66e9f4e3125
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: 6fdba068-796f-8fff-0a69-2fbd8ed5e27c
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: ac04b2a7-6deb-b03b-7bf9-8bba90beaac9
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	partition Dim_HCO = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents("C:\Users\ShrikantPansare\Downloads\Agent Version 0511_ABCD\Agent Version 0511_ABCD\_workspace\UseCase2_test_pbip\UseCase2.SemanticModel\data\federated.0y4y5w00iqd66e183eik10a55045\Extract.Dim!HCO_33E141CEBC4648AB952C00FDC179E092.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"HCO_ID", Int64.Type}, {"HCO_Name", type text}, {"HCO_Type", type text}, {"City", type text}, {"State", type text}, {"ZIP", Int64.Type}, {"Region", type text}, {"Territory", type text}, {"Territory_Name", type text}, {"Latitude", type number}, {"Longitude", type number}, {"Email", type text}, {"Incoming_Referrals", Int64.Type}, {"Outgoing_Referrals", Int64.Type}, {"Patients_Treated", Int64.Type}, {"Patients_Diagnosed", Int64.Type}, {"Patients_Count", Int64.Type}, {"Mistreated_Patients", Int64.Type}, {"Total_HCPs", Int64.Type}, {"Patients_Prescribed", Int64.Type}})
			in
			    ChangedTypes

	annotation PBI_ResultType = Table
