table Time
	lineageTag: 02f50319-745f-67d9-a49b-bb7f3b74e574

	column Value
		dataType: string
		lineageTag: 039d728f-b4e7-e0f2-35b2-9c4e151b5a0c
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Label
		dataType: string
		lineageTag: 6019a450-ad36-acdc-b42b-df6588f48ecb
		summarizeBy: none
		sourceColumn: Label

		annotation SummarizationSetBy = Automatic

	partition Time = m
		mode: import
		source =
			let
			    Source = Table.FromRows({{"Current Sprint", "Current Sprint"}, {"Previous Sprint", "Previous Sprint"}, {"Last 6 Sprints", "Last 6 Sprints"}, {"Last 12 Sprints", "Last 12 Sprints"}, {"Last 20 Sprints", "Last 20 Sprints"}, {"Current YTD", "Current YTD"}, {"Last Year", "Last Year"}, {"Next 2 Sprints", "Next 2 Sprints"}}, type table [#"Value" = text, #"Label" = text])
			in
			    Source

	annotation PBI_ResultType = Table
